{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 🎬 Movie Recap Translator Bot\n",
    "\n",
    "# 🎬 Movie Recap Translator Bot\n",
    "\n",
    "English Audio/Video → Myanmar MovieRecap Style\n",
    "\n",
    "### Workflow:\n",
    "1. English voice/video ပို့ပါ\n",
    "2. Gemini API → transcribe + Myanmar translate\n",
    "3. Myanmar text + Audio ပြန်ပို့"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# Cell 1: Install Dependencies\n",
    "!pip install pyTelegramBotAPI gtts --quiet\n",
    "!apt-get install -y ffmpeg 2>/dev/null | tail -1\n",
    "print(\"✅ Dependencies installed!\")"
   ],
   "outputs": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# Cell 2: Configuration\n",
    "TELEGRAM_BOT_TOKEN = \"8783814558:AAFCIyfcoY8vbvsdpFXXtBbXUgRJhmyKZD8\"\n",
    "GEMINI_API_KEY = \"AQ.Ab8RN6LEq5RgDg3VgoVUQM1_HENOEUe1pSMVczmRROMmgqhx_g\"\n",
    "GEMINI_MODEL = \"gemini-3.5-flash\"\n",
    "GEMINI_BASE_URL = \"https://generativelanguage.googleapis.com/v1beta/models\"\n",
    "MAX_VIDEO_SIZE_MB = 50\n",
    "print(\"✅ Configuration set!\")"
   ],
   "outputs": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "import os\n",
    "import sys\n",
    "import time\n",
    "import json\n",
    "import base64\n",
    "import tempfile\n",
    "import urllib.request\n",
    "import telebot\n",
    "from gtts import gTTS\n",
    "\n",
    "# ============================================================\n",
    "# GEMINI API - v1beta COMPATIBLE\n",
    "# ============================================================\n",
    "\n",
    "def gemini_generate(parts):\n",
    "    \"\"\"\n",
    "    Send request to Gemini API v1beta.\n",
    "    parts format (NO 'type' key):\n",
    "      Text:       {\"text\": \"your text here\"}\n",
    "      Inline:     {\"inline_data\": {\"mime_type\": \"audio/mp3\", \"data\": \"base64...\"}}\n",
    "      File URI:   {\"file_data\": {\"file_uri\": \"...\", \"mime_type\": \"audio/mp3\"}}\n",
    "    \"\"\"\n",
    "    payload = {\n",
    "        \"contents\": [{\"parts\": parts}],\n",
    "        \"generationConfig\": {\n",
    "            \"temperature\": 0.7,\n",
    "            \"maxOutputTokens\": 8192\n",
    "        }\n",
    "    }\n",
    "\n",
    "    url = f\"{GEMINI_BASE_URL}/{GEMINI_MODEL}:generateContent?key={GEMINI_API_KEY}\"\n",
    "    headers = {\"Content-Type\": \"application/json\"}\n",
    "    data = json.dumps(payload).encode('utf-8')\n",
    "\n",
    "    req = urllib.request.Request(url, data=data, headers=headers, method='POST')\n",
    "\n",
    "    try:\n",
    "        with urllib.request.urlopen(req, timeout=300) as response:\n",
    "            result = json.loads(response.read().decode('utf-8'))\n",
    "    except urllib.error.HTTPError as e:\n",
    "        error_body = e.read().decode('utf-8')\n",
    "        return f\"API Error ({e.code}): {error_body}\"\n",
    "    except Exception as e:\n",
    "        return f\"Request Error: {str(e)}\"\n",
    "\n",
    "    # Extract response\n",
    "    if 'candidates' in result and result['candidates']:\n",
    "        candidate = result['candidates'][0]\n",
    "        if 'content' in candidate and 'parts' in candidate['content']:\n",
    "            resp_parts = candidate['content']['parts']\n",
    "            return resp_parts[0]['text'] if resp_parts else \"\"\n",
    "    elif 'error' in result:\n",
    "        return f\"Error: {result['error'].get('message', 'Unknown error')}\"\n",
    "    else:\n",
    "        return \"No response from Gemini.\"\n",
    "\n",
    "\n",
    "def transcribe_file(file_path, file_type=\"audio\"):\n",
    "    \"\"\"Transcribe audio/video file using Gemini API.\"\"\"\n",
    "    file_size_mb = os.path.getsize(file_path) / (1024 * 1024)\n",
    "    print(f\"[Gemini] File size: {file_size_mb:.1f} MB\")\n",
    "\n",
    "    if file_size_mb < 19:\n",
    "        # INLINE: base64 encode file and send directly\n",
    "        mime_type = \"audio/mp3\" if file_type == \"audio\" else \"video/mp4\"\n",
    "\n",
    "        with open(file_path, 'rb') as f:\n",
    "            file_data = base64.b64encode(f.read()).decode('utf-8')\n",
    "\n",
    "        prompt = \"\"\"You are a professional transcription expert. Please:\n",
    "1. Transcribe ALL speech and dialogue from this file accurately\n",
    "2. Identify different speakers if possible\n",
    "3. Include timestamps if available\n",
    "4. Transcribe in the ORIGINAL LANGUAGE\n",
    "5. Be thorough and include all spoken content\n",
    "\n",
    "Provide the complete transcription.\"\"\"\n",
    "\n",
    "        # v1beta format: NO \"type\" key\n",
    "        parts = [\n",
    "            {\"text\": prompt},\n",
    "            {\"inline_data\": {\"mime_type\": mime_type, \"data\": file_data}}\n",
    "        ]\n",
    "        return gemini_generate(parts)\n",
    "\n",
    "    else:\n",
    "        # LARGE FILE: upload to Gemini Files API first\n",
    "        mime_type = \"audio/mp3\" if file_type == \"audio\" else \"video/mp4\"\n",
    "        file_size = os.path.getsize(file_path)\n",
    "\n",
    "        print(\"[Gemini] Uploading to Files API...\")\n",
    "\n",
    "        # Step 1: Initialize upload\n",
    "        upload_url = \"https://generativelanguage.googleapis.com/upload/v1beta/files\"\n",
    "        headers = {\n",
    "            \"x-goog-api-key\": GEMINI_API_KEY,\n",
    "            \"X-Goog-Upload-Protocol\": \"resumable\",\n",
    "            \"X-Goog-Upload-Command\": \"start\",\n",
    "            \"X-Goog-Upload-Header-Content-Length\": str(file_size),\n",
    "            \"X-Goog-Upload-Header-Content-Type\": mime_type,\n",
    "            \"Content-Type\": \"application/json\"\n",
    "        }\n",
    "        data = json.dumps({\"file\": {\"display_name\": \"upload\"}}).encode('utf-8')\n",
    "        req = urllib.request.Request(upload_url, data=data, headers=headers, method='POST')\n",
    "        resp = urllib.request.urlopen(req)\n",
    "        upload_location = resp.headers.get('X-Goog-Upload-URL')\n",
    "\n",
    "        # Step 2: Upload file data\n",
    "        with open(file_path, 'rb') as f:\n",
    "            file_data = f.read()\n",
    "\n",
    "        headers2 = {\n",
    "            \"Content-Length\": str(file_size),\n",
    "            \"X-Goog-Upload-Offset\": \"0\",\n",
    "            \"X-Goog-Upload-Command\": \"upload, finalize\"\n",
    "        }\n",
    "        req2 = urllib.request.Request(upload_location, data=file_data, headers=headers2, method='POST')\n",
    "        resp2 = urllib.request.urlopen(req2)\n",
    "        upload_result = json.loads(resp2.read().decode('utf-8'))\n",
    "\n",
    "        file_uri = upload_result['file']['uri']\n",
    "        file_name = upload_result['file']['name']\n",
    "        print(f\"[Gemini] Uploaded: {file_uri}\")\n",
    "\n",
    "        # Step 3: Wait for processing\n",
    "        for attempt in range(60):\n",
    "            check_url = f\"https://generativelanguage.googleapis.com/v1beta/{file_name}?key={GEMINI_API_KEY}\"\n",
    "            req_check = urllib.request.Request(check_url)\n",
    "            resp_check = urllib.request.urlopen(req_check)\n",
    "            status = json.loads(resp_check.read().decode('utf-8'))\n",
    "            state = status.get('state', '')\n",
    "            print(f\"[Gemini] State: {state} (attempt {attempt + 1})\")\n",
    "            if state == 'ACTIVE':\n",
    "                break\n",
    "            elif state == 'FAILED':\n",
    "                return \"File processing failed.\"\n",
    "            time.sleep(5)\n",
    "\n",
    "        # Step 4: Transcribe\n",
    "        prompt = \"\"\"You are a professional transcription expert. Please:\n",
    "1. Transcribe ALL speech and dialogue from this file accurately\n",
    "2. Identify different speakers if possible\n",
    "3. Include timestamps if available\n",
    "4. Transcribe in the ORIGINAL LANGUAGE\n",
    "5. Be thorough and include all spoken content\n",
    "\n",
    "Provide the complete transcription.\"\"\"\n",
    "\n",
    "        # v1beta format: NO \"type\" key, use \"file_data\" directly\n",
    "        parts = [\n",
    "            {\"text\": prompt},\n",
    "            {\"file_data\": {\"file_uri\": file_uri, \"mime_type\": mime_type}}\n",
    "        ]\n",
    "        return gemini_generate(parts)\n",
    "\n",
    "\n",
    "def translate_to_myanmar(transcription):\n",
    "    \"\"\"Translate English transcription to Myanmar MovieRecap style.\"\"\"\n",
    "    prompt = f\"\"\"You are a professional Myanmar movie recap narrator.\n",
    "\n",
    "Your task: Take the English transcription below and transform it into an exciting, dramatic Myanmar language movie/story recap.\n",
    "\n",
    "RULES:\n",
    "- Write ENTIRELY in Myanmar (မြန်မာ) language\n",
    "- Use the dramatic, engaging storytelling style of Myanmar movie recap YouTube channels\n",
    "- Start with an exciting hook that grabs attention\n",
    "- Tell the story in an exciting, suspenseful way as if narrating a movie\n",
    "- Use colloquial Myanmar storytelling style (ဇာတ်လမ်းပြောပုံ)\n",
    "- Keep ALL important plot points, characters, and events from the original\n",
    "- Make it sound like a professional Myanmar movie recap narration\n",
    "- Write in well-structured paragraphs, NOT bullet points\n",
    "- Be dramatic and exciting - make the audience want to keep reading\n",
    "\n",
    "Here is the English transcription to transform:\n",
    "\n",
    "===\n",
    "{transcription}\n",
    "===\n",
    "\n",
    "Now write the Myanmar MovieRecap style narration:\"\"\"\n",
    "\n",
    "    # v1beta format: just {\"text\": \"...\"}\n",
    "    parts = [{\"text\": prompt}]\n",
    "    return gemini_generate(parts)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# TEXT-TO-SPEECH\n",
    "# ============================================================\n",
    "\n",
    "def text_to_speech_myanmar(text, output_path):\n",
    "    \"\"\"Convert Myanmar text to speech audio file.\"\"\"\n",
    "    clean_text = text.strip()\n",
    "    max_chars = 3000\n",
    "\n",
    "    if len(clean_text) <= max_chars:\n",
    "        try:\n",
    "            tts = gTTS(text=clean_text, lang='my', slow=False)\n",
    "            tts.save(output_path)\n",
    "            print(f\"[TTS] Saved: {output_path}\")\n",
    "            return True\n",
    "        except Exception as e:\n",
    "            print(f\"[TTS] Failed: {e}\")\n",
    "            return False\n",
    "    else:\n",
    "        chunks = [clean_text[i:i+max_chars] for i in range(0, len(clean_text), max_chars)]\n",
    "        print(f\"[TTS] Splitting into {len(chunks)} chunks\")\n",
    "\n",
    "        temp_files = []\n",
    "        for i, chunk in enumerate(chunks):\n",
    "            temp_file = f\"{output_path}.chunk{i}.mp3\"\n",
    "            try:\n",
    "                tts = gTTS(text=chunk, lang='my', slow=False)\n",
    "                tts.save(temp_file)\n",
    "                temp_files.append(temp_file)\n",
    "            except Exception as e:\n",
    "                print(f\"[TTS] Chunk {i} failed: {e}\")\n",
    "\n",
    "        if len(temp_files) == 0:\n",
    "            return False\n",
    "\n",
    "        if len(temp_files) == 1:\n",
    "            os.rename(temp_files[0], output_path)\n",
    "        else:\n",
    "            concat_file = f\"{output_path}.concat.txt\"\n",
    "            with open(concat_file, 'w') as f:\n",
    "                for tf in temp_files:\n",
    "                    f.write(f\"file '{tf}'\\n\")\n",
    "            os.system(f\"ffmpeg -f concat -safe 0 -i {concat_file} -c copy {output_path} -y 2>/dev/null\")\n",
    "            for tf in temp_files:\n",
    "                try: os.remove(tf)\n",
    "                except: pass\n",
    "            try: os.remove(concat_file)\n",
    "            except: pass\n",
    "\n",
    "        return os.path.exists(output_path)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# TELEGRAM BOT\n",
    "# ============================================================\n",
    "\n",
    "bot = telebot.TeleBot(TELEGRAM_BOT_TOKEN)\n",
    "\n",
    "\n",
    "@bot.message_handler(commands=['start'])\n",
    "def send_welcome(message):\n",
    "    welcome = \"\"\"🎬 Movie Recap Translator Bot 🎬\n",
    "\n",
    "မင်္ဂလာပါ! English voice message သို့မဟုတ် video ပို့ပါ။\n",
    "Myanmar MovieRecap style ဇာတ်လမ်းအကျဉ်းချုပ် + Audio ဖြင့် ပြန်ပို့ပေးပါမယ်!\n",
    "\n",
    "⚙️ Commands:\n",
    "/start - Bot အကြောင်း\n",
    "/help - အသုံးပြုနည်း\n",
    "\n",
    "⚠️ Video: 50MB အောက်\n",
    "🎙️ Voice: အကန့်အသတ်မရှိ\"\"\"\n",
    "    bot.reply_to(message, welcome)\n",
    "\n",
    "\n",
    "@bot.message_handler(commands=['help'])\n",
    "def send_help(message):\n",
    "    help_text = \"\"\"📖 အသုံးပြုနည်း\n",
    "\n",
    "🎙️ Voice message ပို့ပါ → Myanmar recap + audio\n",
    "🎬 Video ပို့ပါ → Myanmar recap + audio\n",
    "• Clear English audio works best\n",
    "• Video < 2 min recommended\n",
    "• Max video: 50MB\"\"\"\n",
    "    bot.reply_to(message, help_text)\n",
    "\n",
    "\n",
    "@bot.message_handler(content_types=['voice'])\n",
    "def handle_voice(message):\n",
    "    chat_id = message.chat.id\n",
    "    status = bot.send_message(chat_id, \"🎙️ Voice ရပြီ! Processing...\")\n",
    "\n",
    "    temp_ogg = None\n",
    "    mp3_file = None\n",
    "    audio_file = None\n",
    "\n",
    "    try:\n",
    "        bot.edit_message_text(\"📥 Downloading...\", chat_id, status.message_id)\n",
    "        file_info = bot.get_file(message.voice.file_id)\n",
    "        file_bytes = bot.download_file(file_info.file_path)\n",
    "\n",
    "        temp_ogg = tempfile.mktemp(suffix='.ogg')\n",
    "        with open(temp_ogg, 'wb') as f:\n",
    "            f.write(file_bytes)\n",
    "\n",
    "        mp3_file = tempfile.mktemp(suffix='.mp3')\n",
    "        ret = os.system(f\"ffmpeg -i '{temp_ogg}' -y '{mp3_file}' 2>/dev/null\")\n",
    "        process_file = mp3_file if (ret == 0 and os.path.exists(mp3_file) and os.path.getsize(mp3_file) > 0) else temp_ogg\n",
    "\n",
    "        bot.edit_message_text(\"🤖 Transcribing with Gemini...\", chat_id, status.message_id)\n",
    "        transcription = transcribe_file(process_file, file_type=\"audio\")\n",
    "\n",
    "        if transcription.startswith(\"Error\") or transcription.startswith(\"API Error\"):\n",
    "            bot.send_message(chat_id, f\"❌ Error: {transcription[:500]}\")\n",
    "            return\n",
    "\n",
    "        bot.edit_message_text(\"🇲🇲 Myanmar MovieRecap style ဘာသာပြန်နေပါတယ်...\", chat_id, status.message_id)\n",
    "        myanmar_text = translate_to_myanmar(transcription)\n",
    "\n",
    "        if myanmar_text.startswith(\"Error\") or myanmar_text.startswith(\"API Error\"):\n",
    "            bot.send_message(chat_id, f\"❌ Translation error: {myanmar_text[:500]}\")\n",
    "            return\n",
    "\n",
    "        # Send text\n",
    "        bot.edit_message_text(\"📝 Sending Myanmar text...\", chat_id, status.message_id)\n",
    "        if len(myanmar_text) > 4096:\n",
    "            chunks = [myanmar_text[i:i+4096] for i in range(0, len(myanmar_text), 4096)]\n",
    "            for i, chunk in enumerate(chunks):\n",
    "                if i == 0:\n",
    "                    bot.edit_message_text(f\"🇲🇲 Myanmar Recap (1/{len(chunks)}):\\n\\n{chunk}\", chat_id, status.message_id)\n",
    "                else:\n",
    "                    time.sleep(1)\n",
    "                    bot.send_message(chat_id, f\"🇲🇲 (part {i+1}/{len(chunks)}):\\n\\n{chunk}\")\n",
    "        else:\n",
    "            bot.edit_message_text(f\"🇲🇲 Myanmar Recap:\\n\\n{myanmar_text}\", chat_id, status.message_id)\n",
    "\n",
    "        # Send audio\n",
    "        bot.send_message(chat_id, \"🔊 Audio create လုပ်နေပါတယ်...\")\n",
    "        audio_file = tempfile.mktemp(suffix='.mp3')\n",
    "        if text_to_speech_myanmar(myanmar_text, audio_file):\n",
    "            with open(audio_file, 'rb') as audio:\n",
    "                bot.send_audio(chat_id, audio, caption=\"🔊 Myanmar Audio\", title=\"Myanmar Recap Audio\")\n",
    "        else:\n",
    "            bot.send_message(chat_id, \"⚠️ Audio create မရပါ\")\n",
    "\n",
    "        bot.send_message(chat_id, \"✅ Completed! 🎬\")\n",
    "\n",
    "    except Exception as e:\n",
    "        try:\n",
    "            bot.edit_message_text(f\"❌ Error: {str(e)}\", chat_id, status.message_id)\n",
    "        except:\n",
    "            bot.send_message(chat_id, f\"❌ Error: {str(e)}\")\n",
    "        print(f\"[Error] {e}\")\n",
    "\n",
    "    finally:\n",
    "        for f in [temp_ogg, mp3_file, audio_file]:\n",
    "            if f and os.path.exists(f):\n",
    "                try: os.remove(f)\n",
    "                except: pass\n",
    "\n",
    "\n",
    "@bot.message_handler(content_types=['video'])\n",
    "def handle_video(message):\n",
    "    chat_id = message.chat.id\n",
    "\n",
    "    if hasattr(message.video, 'file_size') and message.video.file_size:\n",
    "        size_mb = message.video.file_size / (1024 * 1024)\n",
    "        if size_mb > MAX_VIDEO_SIZE_MB:\n",
    "            bot.send_message(chat_id, f\"❌ Video ကြီးလွန်းပါတယ်! ({size_mb:.1f}MB / max {MAX_VIDEO_SIZE_MB}MB)\")\n",
    "            return\n",
    "\n",
    "    status = bot.send_message(chat_id, \"🎬 Video ရပြီ! Processing...\")\n",
    "    temp_video = None\n",
    "    audio_file = None\n",
    "\n",
    "    try:\n",
    "        bot.edit_message_text(\"📥 Downloading video...\", chat_id, status.message_id)\n",
    "        file_info = bot.get_file(message.video.file_id)\n",
    "        file_bytes = bot.download_file(file_info.file_path)\n",
    "\n",
    "        temp_video = tempfile.mktemp(suffix='.mp4')\n",
    "        with open(temp_video, 'wb') as f:\n",
    "            f.write(file_bytes)\n",
    "\n",
    "        size_mb = os.path.getsize(temp_video) / (1024 * 1024)\n",
    "        bot.edit_message_text(f\"📊 Video: {size_mb:.1f}MB\\n🤖 Processing...\", chat_id, status.message_id)\n",
    "\n",
    "        bot.edit_message_text(\"🎙️ Transcribing...\", chat_id, status.message_id)\n",
    "        transcription = transcribe_file(temp_video, file_type=\"video\")\n",
    "\n",
    "        if transcription.startswith(\"Error\") or transcription.startswith(\"API Error\"):\n",
    "            bot.send_message(chat_id, f\"❌ Error: {transcription[:500]}\")\n",
    "            return\n",
    "\n",
    "        bot.edit_message_text(\"🇲🇲 Myanmar MovieRecap style ဘာသာပြန်နေပါတယ်...\", chat_id, status.message_id)\n",
    "        myanmar_text = translate_to_myanmar(transcription)\n",
    "\n",
    "        if myanmar_text.startswith(\"Error\") or myanmar_text.startswith(\"API Error\"):\n",
    "            bot.send_message(chat_id, f\"❌ Translation error: {myanmar_text[:500]}\")\n",
    "            return\n",
    "\n",
    "        # Send text\n",
    "        bot.edit_message_text(\"📝 Sending...\", chat_id, status.message_id)\n",
    "        if len(myanmar_text) > 4096:\n",
    "            chunks = [myanmar_text[i:i+4096] for i in range(0, len(myanmar_text), 4096)]\n",
    "            for i, chunk in enumerate(chunks):\n",
    "                if i == 0:\n",
    "                    bot.edit_message_text(f\"🇲🇲 (1/{len(chunks)}):\\n\\n{chunk}\", chat_id, status.message_id)\n",
    "                else:\n",
    "                    time.sleep(1)\n",
    "                    bot.send_message(chat_id, f\"🇲🇲 (part {i+1}/{len(chunks)}):\\n\\n{chunk}\")\n",
    "        else:\n",
    "            bot.edit_message_text(f\"🇲🇲 Myanmar Recap:\\n\\n{myanmar_text}\", chat_id, status.message_id)\n",
    "\n",
    "        # Send audio\n",
    "        bot.send_message(chat_id, \"🔊 Audio create...\")\n",
    "        audio_file = tempfile.mktemp(suffix='.mp3')\n",
    "        if text_to_speech_myanmar(myanmar_text, audio_file):\n",
    "            with open(audio_file, 'rb') as audio:\n",
    "                bot.send_audio(chat_id, audio, caption=\"🔊 Myanmar Audio\", title=\"Myanmar Recap Audio\")\n",
    "        else:\n",
    "            bot.send_message(chat_id, \"⚠️ Audio create မရပါ\")\n",
    "\n",
    "        bot.send_message(chat_id, \"✅ Completed! 🎬\")\n",
    "\n",
    "    except Exception as e:\n",
    "        try:\n",
    "            bot.edit_message_text(f\"❌ Error: {str(e)}\", chat_id, status.message_id)\n",
    "        except:\n",
    "            bot.send_message(chat_id, f\"❌ Error: {str(e)}\")\n",
    "        print(f\"[Error] {e}\")\n",
    "\n",
    "    finally:\n",
    "        for f in [temp_video, audio_file]:\n",
    "            if f and os.path.exists(f):\n",
    "                try: os.remove(f)\n",
    "                except: pass\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# START BOT\n",
    "# ============================================================\n",
    "\n",
    "print(\"=\" * 50)\n",
    "print(\"🎬 MOVIE RECAP TRANSLATOR BOT\")\n",
    "print(\"=\" * 50)\n",
    "\n",
    "if TELEGRAM_BOT_TOKEN == \"YOUR_TELEGRAM_BOT_TOKEN_HERE\":\n",
    "    print(\"❌ Token မသတ်မှတ်ရသေးပါ!\")\n",
    "else:\n",
    "    print(\"✅ Token: Set\")\n",
    "    print(\"✅ Model: gemini-2.0-flash\")\n",
    "    print(\"🚀 Bot starting...\")\n",
    "    bot.infinity_polling(timeout=60, long_polling_timeout=60)\n"
   ],
   "outputs": []
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Quick Guide\n",
    "\n",
    "1. Cell 1 → run (install)\n",
    "2. Cell 2 → run (tokens set)\n",
    "3. Cell 3 → run (bot starts)\n",
    "4. Telegram မှာ voice/video ပို့ပါ\n",
    "\n",
    "Stop: cell ■ button နှိပ်ပါ\n",
    "Restart: Runtime → Restart runtime"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.11.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
