{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 🎬 Movie Recap Translator Bot\n",
    "\n",
    "English Audio/Video → Myanmar MovieRecap Style\n",
    "\n",
    "### Workflow:\n",
    "1. English voice/video ပို့ပါ\n",
    "2. Gemini API → transcribe + Myanmar translate\n",
    "3. Myanmar text + Audio ပြန်ပို့"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# Cell 1: Install Dependencies\n",
    "!pip install pyTelegramBotAPI edge-tts --quiet\n",
    "!apt-get install -y ffmpeg 2>/dev/null | tail -1\n",
    "print(\"✅ Dependencies installed!\")\n"
   ],
   "outputs": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "# Cell 2: Configuration\n",
    "TELEGRAM_BOT_TOKEN = \"8783814558:AAFCIyfcoY8vbvsdpFXXtBbXUgRJhmyKZD8\"\n",
    "GEMINI_API_KEYS = [\n",
    "        \"AQ.Ab8RN6LEq5RgDg3VgoVUQM1_HENOEUe1pSMVczmRROMmgqhx_g\",\n",
    "        \"AQ.Ab8RN6IwCXzS42tpQHfxWKLGF-Tlq0gOo-yvsdr8VCMr6UvGaA\",\n",
    "        \"AQ.Ab8RN6InUIEI1pV5XtomUF4Csr9zLJPbjKzLSV2Lv1Bx8ZSJiA\",\n",
    "        \"AQ.Ab8RN6IvfOrJ0_Qu6HF2fKvNby7ObVQ8lnEo7bn83hHjzrj2Jw\"\n",
    "    ]\n",
    "current_key_index = 0\n",
    "\n",
    "def get_current_key():\n",
    "    return GEMINI_API_KEYS[current_key_index]\n",
    "\n",
    "def rotate_key():\n",
    "    global current_key_index\n",
    "    current_key_index = (current_key_index + 1) % len(GEMINI_API_KEYS)\n",
    "    print(f\"🔄 API Key rotated to Key #{current_key_index + 1}\")\n",
    "    return get_current_key()\n",
    "\n",
    "GEMINI_MODEL = \"gemini-3.5-flash\"\n",
    "!pip install requests urllib3 PyPDF2 --quiet\n",
    "GEMINI_BASE_URL = \"https://generativelanguage.googleapis.com/v1beta/models\"\n",
    "MAX_VIDEO_SIZE_MB = 50\n",
    "print(\"✅ Configuration set!\")\n",
    ""
   ],
   "outputs": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "source": [
    "import os\n",
    "import sys\n",
    "import time\n",
    "import json\n",
    "import base64\n",
    "import tempfile\n",
    "import urllib.request\n",
    "import subprocess\n",
    "from urllib.error import HTTPError, URLError\n",
    "import telebot\n",
    "import edge_tts\n",
    "\n",
    "# ============================================================\n",
    "# RETRY UTILITIES\n",
    "# ============================================================\n",
    "\n",
    "def retry_with_backoff(func, max_retries=10, delay=5, exceptions=(Exception,), chat_id=None):\n",
    "    \"\"\"Retry a function with exponential backoff, handling 429 with Telegram countdown.\"\"\"\n",
    "    for attempt in range(max_retries):\n",
    "        try:\n",
    "            return func()\n",
    "        except exceptions as e:\n",
    "            if attempt == max_retries - 1:\n",
    "                raise\n",
    "            \n",
    "            # Extract status code\n",
    "            status_code = getattr(e, 'code', None)\n",
    "            if status_code is None and hasattr(e, 'response') and e.response is not None:\n",
    "                status_code = getattr(e.response, 'status_code', None)\n",
    "            \n",
    "            if status_code == 429:\n",
    "                num_keys = len(GEMINI_API_KEYS)\n",
    "                if (attempt + 1) % num_keys == 0:\n",
    "                    wait_time = 60 \n",
    "                    print(f\"[RateLimit] All keys exhausted. Waiting {wait_time}s...\")\n",
    "                    if chat_id:\n",
    "                        try:\n",
    "                            msg = bot.send_message(chat_id, f\"⚠️ API Limit ပြည့်သွားလို့ {wait_time}s ခဏစောင့်ပေးပါ... ⏳\")\n",
    "                            for i in range(wait_time, 0, -5):\n",
    "                                time.sleep(5)\n",
    "                                bot.edit_message_text(f\"⚠️ API Limit ပြည့်သွားလို့ {i-5}s ခဏစောင့်ပေးပါ... ⏳\", chat_id, msg.message_id)\n",
    "                            bot.delete_message(chat_id, msg.message_id)\n",
    "                        except: time.sleep(wait_time)\n",
    "                    else:\n",
    "                        time.sleep(wait_time)\n",
    "                else:\n",
    "                    wait_time = 2\n",
    "                    print(f\"[RateLimit] 429 detected. Rotating key...\")\n",
    "                    rotate_key()\n",
    "                    time.sleep(wait_time)\n",
    "            else:\n",
    "                wait_time = delay\n",
    "                print(f\"[Retry] {e} - Retrying in {wait_time}s... (attempt {attempt+1}/{max_retries})\")\n",
    "                delay *= 2\n",
    "                time.sleep(wait_time)\n",
    "\n",
    "# ============================================================\n",
    "# GEMINI API - v1beta COMPATIBLE\n",
    "# ============================================================\n",
    "\n",
    "import requests\n",
    "import urllib.parse\n",
    "\n",
    "def generate_image(prompt):\n",
    "    \"\"\"Generate an image using Pollinations.ai (Free API).\"\"\"\n",
    "    encoded_prompt = urllib.parse.quote(prompt)\n",
    "    image_url = f\"https://pollinations.ai/p/{encoded_prompt}?width=1024&height=1024&seed={int(time.time())}&model=flux\"\n",
    "    return image_url\n",
    "\n",
    "def _do_gemini_request(contents, stream=False):\n",
    "    \"\"\"Execute a Gemini API request with optional streaming.\"\"\"\n",
    "    payload = {\n",
    "        \"contents\": contents,\n",
    "        \"generationConfig\": {\n",
    "            \"temperature\": 0.7,\n",
    "            \"maxOutputTokens\": 16384\n",
    "        }\n",
    "    }\n",
    "    \n",
    "    endpoint = \"streamGenerateContent\" if stream else \"generateContent\"\n",
    "    url = f\"{GEMINI_BASE_URL}/{GEMINI_MODEL}:{endpoint}?key={get_current_key()}\"\n",
    "    \n",
    "    if not stream:\n",
    "        response = requests.post(url, json=payload, timeout=300)\n",
    "        response.raise_for_status()\n",
    "        result = response.json()\n",
    "        if 'candidates' in result and result['candidates']:\n",
    "            candidate = result['candidates'][0]\n",
    "            if 'content' in candidate and 'parts' in candidate['content']:\n",
    "                resp_parts = candidate['content']['parts']\n",
    "                text = resp_parts[0]['text'] if resp_parts else \"\"\n",
    "                if candidate.get('finishReason') == 'MAX_TOKENS':\n",
    "                    text += \"\\\\n\\\\n[⚠️ စာသားရှည်လွန်းသဖြင့် ဒီနေရာမှာတင် ပြတ်တောက်သွားပါသည်။]\"\n",
    "                return text\n",
    "        elif 'error' in result:\n",
    "            return f\"Error: {result['error'].get('message', 'Unknown error')}\"\n",
    "        return \"No response from Gemini.\"\n",
    "    else:\n",
    "        # Streaming logic\n",
    "        def generator():\n",
    "            response = requests.post(url, json=payload, timeout=300, stream=True)\n",
    "            response.raise_for_status()\n",
    "            for line in response.iter_lines():\n",
    "                if line:\n",
    "                    decoded_line = line.decode('utf-8').strip()\n",
    "                    if decoded_line.startswith('\"text\":'):\n",
    "                        # Simple extraction for performance\n",
    "                        text_part = decoded_line.split('\"text\":')[1].strip().strip('\",')\n",
    "                        yield text_part.replace('\\\\n', '\\n').replace('\\\\\"', '\"')\n",
    "                    elif decoded_line.startswith('{') or decoded_line.startswith('['):\n",
    "                        try:\n",
    "                            # Proper JSON parsing for complex parts\n",
    "                            # Handle the leading comma if it's an array of objects\n",
    "                            clean_line = decoded_line.lstrip(',').strip()\n",
    "                            chunk = json.loads(clean_line)\n",
    "                            if 'candidates' in chunk:\n",
    "                                text = chunk['candidates'][0]['content']['parts'][0].get('text', '')\n",
    "                                if text: yield text\n",
    "                        except: pass\n",
    "        return generator()\n",
    "\n",
    "\n",
    "chat_histories = {}\n",
    "\n",
    "def get_history(chat_id):\n",
    "    if chat_id not in chat_histories:\n",
    "        chat_histories[chat_id] = []\n",
    "    return chat_histories[chat_id]\n",
    "\n",
    "def add_to_history(chat_id, role, text, parts=None):\n",
    "    history = get_history(chat_id)\n",
    "    if parts:\n",
    "        history.append({\"role\": role, \"parts\": parts})\n",
    "    else:\n",
    "        history.append({\"role\": role, \"parts\": [{\"text\": text}]})\n",
    "    # Keep last 20 messages for context\n",
    "    if len(history) > 20:\n",
    "        chat_histories[chat_id] = history[-20:]\n",
    "\n",
    "def gemini_generate(contents, stream=False, chat_id=None):\n",
    "    \"\"\"\n",
    "    Send request to Gemini API v1beta with retry logic and optional chat_id for countdown.\n",
    "    \"\"\"\n",
    "    try:\n",
    "        return retry_with_backoff(\n",
    "            lambda: _do_gemini_request(contents, stream=stream),\n",
    "            max_retries=10,\n",
    "            delay=5,\n",
    "            exceptions=(requests.exceptions.RequestException, Exception),\n",
    "            chat_id=chat_id\n",
    "        )\n",
    "    except HTTPError as e:\n",
    "        try:\n",
    "            error_body = e.read().decode('utf-8')\n",
    "            return f\"API Error ({e.code}): {error_body}\"\n",
    "        except:\n",
    "            return f\"API Error ({e.code})\"\n",
    "    except Exception as e:\n",
    "        return f\"Request Error: {str(e)}\"\n",
    "\n",
    "\n",
    "def transcribe_file(file_path, file_type=\"audio\", chat_id=None):\n",
    "    \"\"\"Transcribe audio/video file using Gemini API.\"\"\"\n",
    "    file_size_mb = os.path.getsize(file_path) / (1024 * 1024)\n",
    "    print(f\"[Gemini] File size: {file_size_mb:.1f} MB\")\n",
    "\n",
    "    if file_size_mb < 19:\n",
    "        # INLINE: base64 encode file and send directly\n",
    "        mime_type = \"audio/mp3\" if file_type == \"audio\" else \"video/mp4\"\n",
    "\n",
    "        with open(file_path, 'rb') as f:\n",
    "            file_data = base64.b64encode(f.read()).decode('utf-8')\n",
    "\n",
    "        prompt = \"\"\"You are a professional transcription expert. Please:\n",
    "1. Transcribe ALL speech and dialogue from this file accurately\n",
    "2. Identify different speakers if possible\n",
    "3. Include timestamps if available\n",
    "4. Transcribe in the ORIGINAL LANGUAGE\n",
    "5. Be thorough and include all spoken content\n",
    "\n",
    "Provide the complete transcription.\"\"\"\n",
    "\n",
    "        # v1beta format\n",
    "        contents = [{\n",
    "            \"role\": \"user\",\n",
    "            \"parts\": [\n",
    "                {\"text\": prompt},\n",
    "                {\"inline_data\": {\"mime_type\": mime_type, \"data\": file_data}}\n",
    "            ]\n",
    "        }]\n",
    "        return gemini_generate(contents, chat_id=chat_id)\n",
    "\n",
    "    else:\n",
    "        # LARGE FILE: upload to Gemini Files API first\n",
    "        mime_type = \"audio/mp3\" if file_type == \"audio\" else \"video/mp4\"\n",
    "        file_size = os.path.getsize(file_path)\n",
    "\n",
    "        print(\"[Gemini] Uploading to Files API...\")\n",
    "\n",
    "        # Step 1: Initialize upload\n",
    "        upload_url = \"https://generativelanguage.googleapis.com/upload/v1beta/files\"\n",
    "        headers = {\n",
    "            \"x-goog-api-key\": get_current_key(),\n",
    "            \"X-Goog-Upload-Protocol\": \"resumable\",\n",
    "            \"X-Goog-Upload-Command\": \"start\",\n",
    "            \"X-Goog-Upload-Header-Content-Length\": str(file_size),\n",
    "            \"X-Goog-Upload-Header-Content-Type\": mime_type,\n",
    "            \"Content-Type\": \"application/json\"\n",
    "        }\n",
    "        data = json.dumps({\"file\": {\"display_name\": \"upload\"}}).encode('utf-8')\n",
    "        req = urllib.request.Request(upload_url, data=data, headers=headers, method='POST')\n",
    "        resp = urllib.request.urlopen(req)\n",
    "        upload_location = resp.headers.get('X-Goog-Upload-URL')\n",
    "\n",
    "        # Step 2: Upload file data\n",
    "        with open(file_path, 'rb') as f:\n",
    "            file_data = f.read()\n",
    "\n",
    "        headers2 = {\n",
    "            \"Content-Length\": str(file_size),\n",
    "            \"X-Goog-Upload-Offset\": \"0\",\n",
    "            \"X-Goog-Upload-Command\": \"upload, finalize\"\n",
    "        }\n",
    "        req2 = urllib.request.Request(upload_location, data=file_data, headers=headers2, method='POST')\n",
    "        resp2 = urllib.request.urlopen(req2)\n",
    "        upload_result = json.loads(resp2.read().decode('utf-8'))\n",
    "\n",
    "        file_uri = upload_result['file']['uri']\n",
    "        file_name = upload_result['file']['name']\n",
    "        print(f\"[Gemini] Uploaded: {file_uri}\")\n",
    "\n",
    "        # Step 3: Wait for processing\n",
    "        for attempt in range(60):\n",
    "            check_url = f\"https://generativelanguage.googleapis.com/v1beta/{file_name}?key={get_current_key()}\"\n",
    "            req_check = urllib.request.Request(check_url)\n",
    "            resp_check = urllib.request.urlopen(req_check)\n",
    "            status = json.loads(resp_check.read().decode('utf-8'))\n",
    "            state = status.get('state', '')\n",
    "            print(f\"[Gemini] State: {state} (attempt {attempt + 1})\")\n",
    "            if state == 'ACTIVE':\n",
    "                break\n",
    "            elif state == 'FAILED':\n",
    "                return \"File processing failed.\"\n",
    "            time.sleep(5)\n",
    "\n",
    "        # Step 4: Transcribe\n",
    "        prompt = \"\"\"You are a professional transcription expert. Please:\n",
    "1. Transcribe ALL speech and dialogue from this file accurately\n",
    "2. Identify different speakers if possible\n",
    "3. Include timestamps if available\n",
    "4. Transcribe in the ORIGINAL LANGUAGE\n",
    "5. Be thorough and include all spoken content\n",
    "\n",
    "Provide the complete transcription.\"\"\"\n",
    "\n",
    "        # v1beta format\n",
    "        contents = [{\n",
    "            \"role\": \"user\",\n",
    "            \"parts\": [\n",
    "                {\"text\": prompt},\n",
    "                {\"file_data\": {\"file_uri\": file_uri, \"mime_type\": mime_type}}\n",
    "            ]\n",
    "        }]\n",
    "        return gemini_generate(contents, chat_id=chat_id)\n",
    "\n",
    "\n",
    "def translate_to_myanmar(transcription, duration_sec=None, chat_id=None):\n",
    "    \"\"\"Translate English transcription to Myanmar Thiha Voice MovieRecap style with duration awareness.\"\"\"\n",
    "    \n",
    "    duration_info = \"\"\n",
    "    if duration_sec:\n",
    "        # Average Myanmar speaking speed is roughly 2.5 to 3 words per second for recap style\n",
    "        # We target about 2.8 words per second\n",
    "        target_word_count = int(duration_sec * 2.8)\n",
    "        duration_info = f\"\\\\n- TARGET LENGTH: Approximately {target_word_count} Myanmar words.\\\\n- The original video duration is {int(duration_sec)} seconds. Ensure your narration fits this timeframe (not too short, not too long).\"\n",
    "\n",
    "    prompt = f\"\"\"You are a Myanmar translator with the dramatic storytelling voice of \\\"Thiha Voice\\\" (movie recap channel).\n",
    "\n",
    "IMPORTANT RULES:\n",
    "- ONLY translate what is in the transcription. DO NOT add any extra content, scenes, or information that is not mentioned.\n",
    "- DO NOT invent new plot points, characters, or events.\n",
    "- DO NOT write an intro or outro that is not in the original content.{duration_info}\n",
    "- Provide a COMPREHENSIVE yet EFFICIENT narration. Cover all important details and scenes from the transcription without being overly long-winded.\n",
    "- Maintain a natural movie recap pace - engaging and detailed, but avoiding unnecessary repetition.\n",
    "- Ensure the story flow is smooth and covers the entire content from beginning to end with a good level of detail.\n",
    "\n",
    "SPEAKING STYLE (Thiha Voice tone):\n",
    "- Use dramatic, engaging narration tone - voice ကြမ်းကြမ်း၊ ဆွဲဆွဲငင်ငင်\n",
    "- Use colloquial Myanmar storytelling phrases naturally:\n",
    "  \"ဆိုပြီး...\"\n",
    "  \"ဒီမှာတော့...\"\n",
    "  \"ဆိုတဲ့အခါမှာ...\"\n",
    "  \"ဒါပေမယ့်...\"\n",
    "  \"ဆိုတာကတော့...\"\n",
    "- Be exciting and dramatic but stay faithful to the original content\n",
    "- Write in paragraphs, NOT bullet points\n",
    "- Write ENTIRELY in Myanmar language\n",
    "\n",
    "Here is the English transcription to translate:\n",
    "\n",
    "===\n",
    "{transcription}\n",
    "===\n",
    "\n",
    "Translate the above into Myanmar in Thiha Voice dramatic style. Remember: translate ONLY what's in the transcription, do not add anything extra.\"\"\"\n",
    "\n",
    "    # v1beta format\n",
    "    contents = [{\n",
    "        \"role\": \"user\",\n",
    "        \"parts\": [{\"text\": prompt}]\n",
    "    }]\n",
    "    return gemini_generate(contents, chat_id=chat_id)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# TEXT-TO-SPEECH\n",
    "# ============================================================\n",
    "\n",
    "# ============================================================\n",
    "# USER VOICE SETTINGS\n",
    "# ============================================================\n",
    "\n",
    "# Default settings\n",
    "DEFAULT_VOICE = \"my-MM-ThihaNeural\"\n",
    "DEFAULT_SPEED = 55   # 1-100 (Slightly faster to match video length)\n",
    "DEFAULT_PITCH = 50   # 1-100 (50 = normal)\n",
    "\n",
    "# Per-user settings storage: {chat_id: {\"voice\": ..., \"speed\": ..., \"pitch\": ...}}\n",
    "user_settings = {}\n",
    "\n",
    "def get_user_settings(chat_id):\n",
    "    \"\"\"Get user settings with defaults.\"\"\"\n",
    "    if chat_id not in user_settings:\n",
    "        user_settings[chat_id] = {\n",
    "            \"voice\": DEFAULT_VOICE,\n",
    "            \"speed\": DEFAULT_SPEED,\n",
    "            \"pitch\": DEFAULT_PITCH\n",
    "        }\n",
    "    return user_settings[chat_id]\n",
    "\n",
    "def speed_to_edge_rate(speed):\n",
    "    \"\"\"Convert speed 1-100 to Edge TTS rate percentage.\n",
    "    1 = -50%, 50 = +0%, 100 = +100%\n",
    "    Edge TTS requires + or - sign.\"\"\"\n",
    "    val = int((speed - 50) * 2)\n",
    "    return f\"+{val}%\" if val >= 0 else f\"{val}%\"\n",
    "\n",
    "def pitch_to_edge_hz(pitch):\n",
    "    \"\"\"Convert pitch 1-100 to Edge TTS Hz.\n",
    "    1 = -100Hz, 50 = +0Hz, 100 = +100Hz\n",
    "    Edge TTS requires + or - sign.\"\"\"\n",
    "    val = int((pitch - 50) * 2)\n",
    "    return f\"+{val}Hz\" if val >= 0 else f\"{val}Hz\"\n",
    "\n",
    "# Available Myanmar voices\n",
    "VOICES = {\n",
    "    \"thiha\": \"my-MM-ThihaNeural\",\n",
    "    \"nilar\": \"my-MM-NilarNeural\"\n",
    "}\n",
    "\n",
    "async def _generate_single_chunk(text, output_path, voice=None, speed=50, pitch=50):\n",
    "    \"\"\"Generate audio for a single text chunk with per-user settings.\"\"\"\n",
    "    v = voice or DEFAULT_VOICE\n",
    "    rate = speed_to_edge_rate(speed)\n",
    "    pitch_hz = pitch_to_edge_hz(pitch)\n",
    "    communicate = edge_tts.Communicate(text, v, rate=rate, pitch=pitch_hz)\n",
    "    await communicate.save(output_path)\n",
    "    return True\n",
    "\n",
    "def text_to_speech_myanmar(text, output_path, chat_id=None):\n",
    "    \"\"\"Convert Myanmar text to speech audio file using Edge TTS (ThihaNeural voice).\n",
    "    \n",
    "    Splits long text into chunks and concatenates audio files.\n",
    "    Uses per-user voice settings if chat_id is provided.\n",
    "    \"\"\"\n",
    "    clean_text = text.strip()\n",
    "\n",
    "    if not clean_text:\n",
    "        print(\"[TTS] No text to convert\")\n",
    "        return False\n",
    "\n",
    "    import asyncio\n",
    "    import tempfile\n",
    "\n",
    "    # Chunk size for Edge TTS - split by sentences for natural flow\n",
    "    MAX_CHUNK = 2000  # chars per chunk for Edge TTS\n",
    "    temp_dir = tempfile.mkdtemp()\n",
    "    temp_audio_files = []\n",
    "\n",
    "    try:\n",
    "        # Split text into chunks by sentences\n",
    "        chunks = []\n",
    "        if len(clean_text) <= MAX_CHUNK:\n",
    "            chunks = [clean_text]\n",
    "        else:\n",
    "            # Split by Myanmar sentence markers\n",
    "            sentence_endings = ['။', '\\n', '. ', '! ', '? ']\n",
    "            sentences = [clean_text]\n",
    "            for ending in sentence_endings:\n",
    "                new_sentences = []\n",
    "                for s in sentences:\n",
    "                    parts = s.split(ending)\n",
    "                    new_sentences.extend(parts)\n",
    "                sentences = new_sentences\n",
    "            \n",
    "            # Group sentences into chunks\n",
    "            current_chunk = \"\"\n",
    "            for sentence in sentences:\n",
    "                sentence = sentence.strip()\n",
    "                if not sentence:\n",
    "                    continue\n",
    "                if len(current_chunk) + len(sentence) > MAX_CHUNK:\n",
    "                    if current_chunk:\n",
    "                        chunks.append(current_chunk)\n",
    "                    # If single sentence too long, split by character\n",
    "                    if len(sentence) > MAX_CHUNK:\n",
    "                        for i in range(0, len(sentence), MAX_CHUNK):\n",
    "                            chunks.append(sentence[i:i+MAX_CHUNK])\n",
    "                    else:\n",
    "                        current_chunk = sentence\n",
    "                else:\n",
    "                    if current_chunk:\n",
    "                        current_chunk += ending.strip()\n",
    "                    current_chunk += sentence\n",
    "            if current_chunk:\n",
    "                chunks.append(current_chunk)\n",
    "\n",
    "        print(f\"[TTS] Splitting into {len(chunks)} chunks\")\n",
    "\n",
    "        loop = asyncio.new_event_loop()\n",
    "        asyncio.set_event_loop(loop)\n",
    "        try:\n",
    "            tasks = []\n",
    "            # Get per-user settings\n",
    "            user_voice = DEFAULT_VOICE\n",
    "            user_speed = DEFAULT_SPEED\n",
    "            user_pitch = DEFAULT_PITCH\n",
    "            if chat_id and chat_id in user_settings:\n",
    "                us = user_settings[chat_id]\n",
    "                user_voice = us.get(\"voice\", DEFAULT_VOICE)\n",
    "                user_speed = us.get(\"speed\", DEFAULT_SPEED)\n",
    "                user_pitch = us.get(\"pitch\", DEFAULT_PITCH)\n",
    "            \n",
    "            for i, chunk in enumerate(chunks):\n",
    "                chunk = chunk.strip()\n",
    "                if not chunk: continue\n",
    "                temp_file = os.path.join(temp_dir, f\"chunk_{i:03d}.mp3\")\n",
    "                temp_audio_files.append(temp_file)\n",
    "                tasks.append(_generate_single_chunk(chunk, temp_file, voice=user_voice, speed=user_speed, pitch=user_pitch))\n",
    "            \n",
    "            print(f\"[TTS] Parallel processing {len(tasks)} chunks...\")\n",
    "            loop.run_until_complete(asyncio.gather(*tasks))\n",
    "            # Filter only successful files\n",
    "            temp_audio_files = [f for f in temp_audio_files if os.path.exists(f) and os.path.getsize(f) > 0]\n",
    "        finally:\n",
    "            loop.close()\n",
    "\n",
    "        if len(temp_audio_files) == 0:\n",
    "            print(\"[TTS] ❌ No audio chunks generated\")\n",
    "            return False\n",
    "\n",
    "        # Concatenate all chunks\n",
    "        if len(temp_audio_files) == 1:\n",
    "            os.rename(temp_audio_files[0], output_path)\n",
    "        else:\n",
    "            # Use ffmpeg to concatenate all mp3 files\n",
    "            concat_list = os.path.join(temp_dir, \"concat.txt\")\n",
    "            with open(concat_list, 'w') as f:\n",
    "                for tf in temp_audio_files:\n",
    "                    f.write(f\"file '{tf}'\\n\")\n",
    "            \n",
    "            cmd = f\"ffmpeg -f concat -safe 0 -i {concat_list} -c copy {output_path} -y 2>/dev/null\"\n",
    "            os.system(cmd)\n",
    "\n",
    "            # Verify output exists\n",
    "            if not os.path.exists(output_path) or os.path.getsize(output_path) == 0:\n",
    "                # Fallback: just use the first chunk\n",
    "                print(\"[TTS] ⚠️ Concat failed, using first chunk only\")\n",
    "                os.rename(temp_audio_files[0], output_path)\n",
    "            else:\n",
    "                print(f\"[TTS] ✅ Concatenated {len(temp_audio_files)} chunks\")\n",
    "\n",
    "        if os.path.exists(output_path) and os.path.getsize(output_path) > 0:\n",
    "            size_kb = os.path.getsize(output_path) / 1024\n",
    "            print(f\"[TTS] ✅ ThihaNeural audio saved: {output_path} ({size_kb:.1f} KB)\")\n",
    "            return True\n",
    "        else:\n",
    "            print(\"[TTS] ❌ Audio file empty or missing\")\n",
    "            return False\n",
    "    except Exception as e:\n",
    "        print(f\"[TTS] ❌ Failed: {e}\")\n",
    "        return False\n",
    "    finally:\n",
    "        # Cleanup temp files\n",
    "        import shutil\n",
    "        try:\n",
    "            shutil.rmtree(temp_dir, ignore_errors=True)\n",
    "        except:\n",
    "            pass\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# SRT SUBTITLE GENERATOR\n",
    "# ============================================================\n",
    "\n",
    "def generate_srt(text, output_path, audio_duration=None):\n",
    "    \"\"\"Generate SRT subtitle file from Myanmar text.\n",
    "    \n",
    "    Splits text into sentences and creates timed subtitles.\n",
    "    If audio_duration is provided, distributes time evenly.\n",
    "    Otherwise uses estimated timing based on word count.\n",
    "    \"\"\"\n",
    "    import re\n",
    "    \n",
    "    clean_text = text.strip()\n",
    "    if not clean_text:\n",
    "        return False\n",
    "    \n",
    "    # Split by Myanmar sentence markers\n",
    "    sentence_endings = ['။', '. ', '! ', '? ', '\\n']\n",
    "    sentences = [clean_text]\n",
    "    for ending in sentence_endings:\n",
    "        new_s = []\n",
    "        for s in sentences:\n",
    "            parts = s.split(ending)\n",
    "            new_s.extend(parts)\n",
    "        sentences = new_s\n",
    "    \n",
    "    # Clean up empty sentences\n",
    "    sentences = [s.strip() for s in sentences if s.strip()]\n",
    "    \n",
    "    if not sentences:\n",
    "        sentences = [clean_text]\n",
    "    \n",
    "    def format_srt_time(seconds):\n",
    "        \"\"\"Convert seconds to SRT time format: HH:MM:SS,mmm\"\"\"\n",
    "        hours = int(seconds // 3600)\n",
    "        minutes = int((seconds % 3600) // 60)\n",
    "        secs = int(seconds % 60)\n",
    "        millis = int((seconds % 1) * 1000)\n",
    "        return f\"{hours:02d}:{minutes:02d}:{secs:02d},{millis:03d}\"\n",
    "\n",
    "    # Generate SRT content with weighted timing\n",
    "    srt_lines = []\n",
    "    current_time = 0.5  # Start after 0.5 seconds\n",
    "    \n",
    "    if audio_duration and audio_duration > 0:\n",
    "        total_chars = sum(len(s) for s in sentences)\n",
    "        # Available time after removing initial delay and small gaps (0.1s) between sentences\n",
    "        available_time = audio_duration - 0.5 - (len(sentences) * 0.1)\n",
    "        if available_time < 0: available_time = audio_duration # Fallback\n",
    "        \n",
    "        for i, sentence in enumerate(sentences):\n",
    "            char_ratio = len(sentence) / total_chars\n",
    "            duration = available_time * char_ratio\n",
    "            \n",
    "            start_time = current_time\n",
    "            end_time = current_time + duration\n",
    "            current_time = end_time + 0.1 # Small gap\n",
    "            \n",
    "            srt_lines.append(str(i + 1))\n",
    "            srt_lines.append(f\"{format_srt_time(start_time)} --> {format_srt_time(end_time)}\")\n",
    "            srt_lines.append(sentence)\n",
    "            srt_lines.append(\"\")\n",
    "    else:\n",
    "        # Fallback to estimated timing\n",
    "        for i, sentence in enumerate(sentences):\n",
    "            duration = max(2.0, len(sentence) / 15.0) # ~15 chars per second\n",
    "            start_time = current_time\n",
    "            end_time = current_time + duration\n",
    "            current_time = end_time + 0.3\n",
    "            \n",
    "            srt_lines.append(str(i + 1))\n",
    "            srt_lines.append(f\"{format_srt_time(start_time)} --> {format_srt_time(end_time)}\")\n",
    "            srt_lines.append(sentence)\n",
    "            srt_lines.append(\"\")\n",
    "    \n",
    "    srt_content = \"\\n\".join(srt_lines)\n",
    "    \n",
    "    with open(output_path, 'w', encoding='utf-8') as f:\n",
    "        f.write(srt_content)\n",
    "    \n",
    "    print(f\"[SRT] ✅ Subtitle file saved: {output_path} ({len(sentences)} subtitles)\")\n",
    "    return True\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# TELEGRAM BOT\n",
    "# ============================================================\n",
    "\n",
    "bot = telebot.TeleBot(TELEGRAM_BOT_TOKEN)\n",
    "\n",
    "\n",
    "def safe_send(chat_id, text, status_msg_id=None, is_edit=False):\n",
    "    \"\"\"\n",
    "    Safely send a message with retry logic, splitting into chunks if > 4000 chars.\n",
    "    Returns the last message_id for editing.\n",
    "    \"\"\"\n",
    "    MAX_LEN = 3800\n",
    "    total_len = len(text)\n",
    "    \n",
    "    def _send_chunk(chunk_text, msg_id=None):\n",
    "        for attempt in range(3):\n",
    "            try:\n",
    "                if msg_id:\n",
    "                    return bot.edit_message_text(chunk_text, chat_id, msg_id).message_id\n",
    "                else:\n",
    "                    return bot.send_message(chat_id, chunk_text).message_id\n",
    "            except:\n",
    "                time.sleep(2)\n",
    "        return None\n",
    "\n",
    "    if total_len <= MAX_LEN:\n",
    "        return _send_chunk(text, status_msg_id if is_edit else None)\n",
    "    else:\n",
    "        if is_edit and status_msg_id:\n",
    "            bot.edit_message_text(\"📝 စာသားရှည်လွန်းလို့ အပိုင်းလိုက် ခွဲပို့ပေးပါမယ်...\", chat_id, status_msg_id)\n",
    "        \n",
    "        chunks = [text[i:i+MAX_LEN] for i in range(0, total_len, MAX_LEN)]\n",
    "        num_chunks = len(chunks)\n",
    "        for i, chunk in enumerate(chunks):\n",
    "            header = f\"🇲🇲 Part ({i+1}/{num_chunks})\\\\n\" + (\"=\"*15) + \"\\\\n\\\\n\"\n",
    "            _send_chunk(header + chunk)\n",
    "            time.sleep(1)\n",
    "        return status_msg_id\n",
    "\n",
    "\n",
    "@bot.message_handler(commands=['start'])\n",
    "def send_welcome(message):\n",
    "    welcome = \"\"\"🎬 Movie Recap Translator Bot 🎬\n",
    "\n",
    "မင်္ဂလာပါ! English voice message သို့မဟုတ် video ပို့ပါ။\n",
    "Myanmar MovieRecap style ဇာတ်လမ်းအကျဉ်းချုပ် + Audio ဖြင့် ပြန်ပို့ပေးပါမယ်!\n",
    "\n",
    "⚙️ Commands:\n",
    "/start - Bot အကြောင်း\n",
    "/help - အသုံးပြုနည်း\n",
    "/settings - အသံ Settings (buttons နဲ့ ပြောင်းရန်)\n",
    "📝 SRT Subtitle auto ပို့ပေးပါတယ် (CapCut)\n",
    "\n",
    "⚠️ Video: 50MB အောက်\n",
    "🎙️ Voice: အကန့်အသတ်မရှိ\"\"\"\n",
    "    bot.reply_to(message, welcome)\n",
    "\n",
    "\n",
    "@bot.message_handler(commands=['help'])\n",
    "def send_help(message):\n",
    "    help_text = \"\"\"📖 အသုံးပြုနည်း\n",
    "\n",
    "🎙️ Voice message ပို့ပါ → Myanmar recap + audio\n",
    "🎬 Video ပို့ပါ → Myanmar recap + audio\n",
    "\n",
    "⚙️ အသံ Settings:\n",
    "/voice thiha - Thiha Voice (male)\n",
    "/voice nilar - Nilar Voice (female)\n",
    "/speed 1-100 - အမြန်နှုန်း (50=ပုံမှန်, 1=အဖြေးဆုံး, 100=အမြန်ဆုံး)\n",
    "/pitch 1-100 - အသံနိမ့်မြင့် (50=ပုံမှန်, 1=အနိမ့်ဆုံး, 100=အမြင့်ဆုံး)\n",
    "/settings - လက်ရှိ settings ကြည့်ရန်\n",
    "\n",
    "• Clear English audio works best\n",
    "• Video < 2 min recommended\n",
    "• Max video: 50MB\"\"\"\n",
    "    bot.reply_to(message, help_text)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# INLINE KEYBOARD SETTINGS\n",
    "# ============================================================\n",
    "from telebot import types\n",
    "\n",
    "def build_settings_keyboard(chat_id, include_start_skip=True):\n",
    "    \"\"\"Build inline keyboard for voice settings.\n",
    "    include_start_skip: if True, add Start/Skip buttons at top/bottom.\"\"\"\n",
    "    settings = get_user_settings(chat_id)\n",
    "    \n",
    "    # Voice buttons\n",
    "    voice_name = \"Unknown\"\n",
    "    for name, voice_id in VOICES.items():\n",
    "        if settings[\"voice\"] == voice_id:\n",
    "            voice_name = name.capitalize()\n",
    "            break\n",
    "    \n",
    "    keyboard = types.InlineKeyboardMarkup(row_width=2)\n",
    "    \n",
    "    # Start button FIRST (top) if requested\n",
    "    if include_start_skip:\n",
    "        keyboard.add(types.InlineKeyboardButton(\"▶️ Start Processing\", callback_data=\"start_processing\"))\n",
    "    \n",
    "    # Voice selection\n",
    "    thiha_cb = types.InlineKeyboardButton(\"✅ Thiha\" if \"Thiha\" in voice_name else \"🎙️ Thiha\", callback_data=\"voice_thiha\")\n",
    "    nilar_cb = types.InlineKeyboardButton(\"✅ Nilar\" if \"Nilar\" in voice_name else \"🎙️ Nilar\", callback_data=\"voice_nilar\")\n",
    "    keyboard.add(thiha_cb, nilar_cb)\n",
    "    \n",
    "    # Speed row\n",
    "    keyboard.add(types.InlineKeyboardButton(\"⚡ Speed: \" + str(settings['speed']), callback_data=\"noop\"))\n",
    "    speed_row = [types.InlineKeyboardButton(\"-10\", callback_data=\"speed_-10\")]\n",
    "    for s in [20, 30, 40, 50, 60, 70, 80]:\n",
    "        btn = types.InlineKeyboardButton(str(s) if settings['speed'] != s else \"[\" + str(s) + \"]\", callback_data=\"speed_\" + str(s))\n",
    "        speed_row.append(btn)\n",
    "    speed_row.append(types.InlineKeyboardButton(\"+10\", callback_data=\"speed_+10\"))\n",
    "    keyboard.add(*speed_row)\n",
    "    \n",
    "    # Pitch row\n",
    "    keyboard.add(types.InlineKeyboardButton(\"🎵 Pitch: \" + str(settings['pitch']), callback_data=\"noop\"))\n",
    "    pitch_row = [types.InlineKeyboardButton(\"-10\", callback_data=\"pitch_-10\")]\n",
    "    for p in [20, 30, 40, 50, 60, 70, 80]:\n",
    "        btn = types.InlineKeyboardButton(str(p) if settings['pitch'] != p else \"[\" + str(p) + \"]\", callback_data=\"pitch_\" + str(p))\n",
    "        pitch_row.append(btn)\n",
    "    pitch_row.append(types.InlineKeyboardButton(\"+10\", callback_data=\"pitch_+10\"))\n",
    "    keyboard.add(*pitch_row)\n",
    "    \n",
    "    # Skip button LAST (bottom) if requested\n",
    "    if include_start_skip:\n",
    "        keyboard.add(types.InlineKeyboardButton(\"⏭️ Skip (Default)\", callback_data=\"skip_settings\"))\n",
    "        keyboard.add(types.InlineKeyboardButton(\"💡 Ask AI about this\", callback_data=\"ask_ai_media\"))\n",
    "    \n",
    "    return keyboard\n",
    "\n",
    "\n",
    "@bot.message_handler(commands=['settings'])\n",
    "def show_settings(message):\n",
    "    \"\"\"Show settings with inline keyboard.\"\"\"\n",
    "    chat_id = message.chat.id\n",
    "    settings = get_user_settings(chat_id)\n",
    "    \n",
    "    voice_name = \"Unknown\"\n",
    "    for name, voice_id in VOICES.items():\n",
    "        if settings[\"voice\"] == voice_id:\n",
    "            voice_name = name.capitalize()\n",
    "            break\n",
    "    \n",
    "    rate = speed_to_edge_rate(settings[\"speed\"])\n",
    "    pitch_hz = pitch_to_edge_hz(settings[\"pitch\"])\n",
    "    \n",
    "    info = \"⚙️ Voice Settings\\n\\n🎙️ Voice: \" + voice_name + \"\\n⚡ Speed: \" + str(settings['speed']) + \" (\" + rate + \")\\n   1=အဖြေးဆုံး | 50=ပုံမှန် | 100=အမြန်ဆုံး\\n🎵 Pitch: \" + str(settings['pitch']) + \" (\" + pitch_hz + \")\\n   1=အနိမ့်ဆုံး | 50=ပုံမှန် | 100=အမြင့်ဆုံး\\n\\n👇 Buttons နှိပ်ပြီး ပြောင်းပါ\"\n",
    "    \n",
    "    keyboard = build_settings_keyboard(chat_id, include_start_skip=False)\n",
    "    bot.send_message(chat_id, info, reply_markup=keyboard)\n",
    "\n",
    "\n",
    "@bot.callback_query_handler(func=lambda call: True)\n",
    "def handle_callback(call):\n",
    "    \"\"\"Handle inline keyboard button presses.\"\"\"\n",
    "    chat_id = call.message.chat.id\n",
    "    data = call.data\n",
    "    \n",
    "    # Voice selection\n",
    "    if data.startswith(\"voice_\"):\n",
    "        voice_name = data.replace(\"voice_\", \"\")\n",
    "        if voice_name in VOICES:\n",
    "            settings = get_user_settings(chat_id)\n",
    "            settings[\"voice\"] = VOICES[voice_name]\n",
    "            # Update keyboard\n",
    "            info = \"⚙️ Voice Settings\\n\\n🎙️ Voice: \" + voice_name.capitalize() + \"\\n✅ အသံ ပြောင်းပြီးပါပြီ!\\n\\n👇 နောက်ထပ် ပြောင်းချင်ရင် buttons နှိပ်ပါ\"\n",
    "            keyboard = build_settings_keyboard(chat_id, include_start_skip=(chat_id in pending_requests))\n",
    "            try:\n",
    "                bot.edit_message_text(info, chat_id, call.message.message_id, reply_markup=keyboard)\n",
    "            except:\n",
    "                bot.send_message(chat_id, info, reply_markup=keyboard)\n",
    "        bot.answer_callback_query(call.id)\n",
    "    \n",
    "    # Speed adjustment\n",
    "    elif data.startswith(\"speed_\"):\n",
    "        val_str = data.replace(\"speed_\", \"\")\n",
    "        settings = get_user_settings(chat_id)\n",
    "        \n",
    "        if val_str in [\"+10\", \"-10\"]:\n",
    "            delta = 10 if val_str == \"+10\" else -10\n",
    "            new_speed = max(1, min(100, settings[\"speed\"] + delta))\n",
    "        else:\n",
    "            try:\n",
    "                new_speed = int(val_str)\n",
    "            except:\n",
    "                bot.answer_callback_query(call.id, \"Invalid\")\n",
    "                return\n",
    "        \n",
    "        settings[\"speed\"] = new_speed\n",
    "        rate = speed_to_edge_rate(new_speed)\n",
    "        \n",
    "        voice_name = \"Unknown\"\n",
    "        for name, voice_id in VOICES.items():\n",
    "            if settings[\"voice\"] == voice_id:\n",
    "                voice_name = name.capitalize()\n",
    "                break\n",
    "        \n",
    "        pitch_hz = pitch_to_edge_hz(settings[\"pitch\"])\n",
    "        info = \"⚙️ Voice Settings\\n\\n🎙️ Voice: \" + voice_name + \"\\n⚡ Speed: \" + str(new_speed) + \" (\" + rate + \")\\n   1=အဖြေးဆုံး | 50=ပုံမှန် | 100=အမြန်ဆုံး\\n🎵 Pitch: \" + str(settings['pitch']) + \" (\" + pitch_hz + \")\\n   1=အနိမ့်ဆုံး | 50=ပုံမှန် | 100=အမြင့်ဆုံး\\n\\n👇 Buttons နှိပ်ပြီး ပြောင်းပါ\"\n",
    "        \n",
    "        has_pending = chat_id in pending_requests\n",
    "        keyboard = build_settings_keyboard(chat_id, include_start_skip=has_pending)\n",
    "        try:\n",
    "            bot.edit_message_text(info, chat_id, call.message.message_id, reply_markup=keyboard)\n",
    "        except:\n",
    "            bot.send_message(chat_id, info, reply_markup=keyboard)\n",
    "        bot.answer_callback_query(call.id)\n",
    "    \n",
    "    # Pitch adjustment\n",
    "    elif data.startswith(\"pitch_\"):\n",
    "        val_str = data.replace(\"pitch_\", \"\")\n",
    "        settings = get_user_settings(chat_id)\n",
    "        \n",
    "        if val_str in [\"+10\", \"-10\"]:\n",
    "            delta = 10 if val_str == \"+10\" else -10\n",
    "            new_pitch = max(1, min(100, settings[\"pitch\"] + delta))\n",
    "        else:\n",
    "            try:\n",
    "                new_pitch = int(val_str)\n",
    "            except:\n",
    "                bot.answer_callback_query(call.id, \"Invalid\")\n",
    "                return\n",
    "        \n",
    "        settings[\"pitch\"] = new_pitch\n",
    "        pitch_hz = pitch_to_edge_hz(new_pitch)\n",
    "        \n",
    "        voice_name = \"Unknown\"\n",
    "        for name, voice_id in VOICES.items():\n",
    "            if settings[\"voice\"] == voice_id:\n",
    "                voice_name = name.capitalize()\n",
    "                break\n",
    "        \n",
    "        rate = speed_to_edge_rate(settings[\"speed\"])\n",
    "        info = \"⚙️ Voice Settings\\n\\n🎙️ Voice: \" + voice_name + \"\\n⚡ Speed: \" + str(settings['speed']) + \" (\" + rate + \")\\n   1=အဖြေးဆုံး | 50=ပုံမှန် | 100=အမြန်ဆုံး\\n🎵 Pitch: \" + str(new_pitch) + \" (\" + pitch_hz + \")\\n   1=အနိမ့်ဆုံး | 50=ပုံမှန် | 100=အမြင့်ဆုံး\\n\\n👇 Buttons နှိပ်ပြီး ပြောင်းပါ\"\n",
    "        \n",
    "        has_pending = chat_id in pending_requests\n",
    "        keyboard = build_settings_keyboard(chat_id, include_start_skip=has_pending)\n",
    "        try:\n",
    "            bot.edit_message_text(info, chat_id, call.message.message_id, reply_markup=keyboard)\n",
    "        except:\n",
    "            bot.send_message(chat_id, info, reply_markup=keyboard)\n",
    "        bot.answer_callback_query(call.id)\n",
    "    \n",
    "    # Start processing\n",
    "    elif data == \"start_processing\":\n",
    "        if chat_id in pending_requests:\n",
    "            pending = pending_requests.pop(chat_id)\n",
    "            settings_msg_id = call.message.message_id\n",
    "            bot.edit_message_text(\"🚀 Processing စလုပ်ပါပြီ...\", chat_id, settings_msg_id, reply_markup=None)\n",
    "            process_media(chat_id, pending[\"media_type\"], pending[\"file_data\"], settings_msg_id)\n",
    "        else:\n",
    "            bot.answer_callback_query(call.id, \"⚠️ Media မရှိပါ\")\n",
    "        bot.answer_callback_query(call.id)\n",
    "    \n",
    "    # Skip settings - use default and process\n",
    "    elif data == \"skip_settings\":\n",
    "        if chat_id in pending_requests:\n",
    "            pending = pending_requests.pop(chat_id)\n",
    "            settings_msg_id = call.message.message_id\n",
    "            bot.edit_message_text(\"⏭️ Default settings နဲ့ Processing...\", chat_id, settings_msg_id, reply_markup=None)\n",
    "            process_media(chat_id, pending[\"media_type\"], pending[\"file_data\"], settings_msg_id)\n",
    "        else:\n",
    "            bot.answer_callback_query(call.id, \"⚠️ Media မရှိပါ\")\n",
    "        bot.answer_callback_query(call.id)\n",
    "    \n",
    "    # Ask AI about media\n",
    "    elif data == \"ask_ai_media\":\n",
    "        if chat_id in pending_requests:\n",
    "            bot.edit_message_text(\"💬 ဒီ Media နဲ့ ပတ်သက်ပြီး ဘာသိချင်ပါသလဲ? (စာရိုက်ပြီး မေးနိုင်ပါပြီ)\", chat_id, call.message.message_id)\n",
    "            pending_requests[chat_id][\"awaiting_question\"] = True\n",
    "        bot.answer_callback_query(call.id)\n",
    "        \n",
    "    # No-op (for label buttons)\n",
    "    elif data == \"noop\":\n",
    "        bot.answer_callback_query(call.id)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# PENDING MEDIA STORAGE\n",
    "# ============================================================\n",
    "pending_requests = {}\n",
    "\n",
    "\n",
    "def show_settings_for_processing(chat_id, media_type, file_data):\n",
    "    \"\"\"Show settings keyboard and store pending media info.\"\"\"\n",
    "    settings = get_user_settings(chat_id)\n",
    "    \n",
    "    voice_name = \"Unknown\"\n",
    "    for name, voice_id in VOICES.items():\n",
    "        if settings[\"voice\"] == voice_id:\n",
    "            voice_name = name.capitalize()\n",
    "            break\n",
    "    \n",
    "    rate = speed_to_edge_rate(settings[\"speed\"])\n",
    "    pitch_hz = pitch_to_edge_hz(settings[\"pitch\"])\n",
    "    \n",
    "    emoji = \"🎙️\" if media_type == \"voice\" else \"🎬\"\n",
    "    msg = emoji + \" \" + (\"Voice ရပြီ!\" if media_type == \"voice\" else \"Video ရပြီ!\") + \"\\n\\n⚙️ အသံ Settings ရွေးပါ:\\n\\n🎙️ Voice: \" + voice_name + \"\\n⚡ Speed: \" + str(settings['speed']) + \" (\" + rate + \")\\n🎵 Pitch: \" + str(settings['pitch']) + \" (\" + pitch_hz + \")\\n\\n👇 Settings ပြောင်းပါ၊ ✅ ပြီးရင် Start နှိပ်ပါ\\n⏭️ ပြောင်းမယ်မဆိုရင် Skip နှိပ်ပါ\"\n",
    "    \n",
    "    # Store pending request\n",
    "    pending_requests[chat_id] = {\n",
    "        \"media_type\": media_type,\n",
    "        \"file_data\": file_data\n",
    "    }\n",
    "    \n",
    "    # Build keyboard - Start button first, then settings, then Skip\n",
    "    keyboard = types.InlineKeyboardMarkup(row_width=2)\n",
    "    \n",
    "    # Start button FIRST (top)\n",
    "    start_btn = types.InlineKeyboardButton(\"▶️ Start Processing\", callback_data=\"start_processing\")\n",
    "    keyboard.add(start_btn)\n",
    "    \n",
    "    # Voice selection\n",
    "    thiha_cb = types.InlineKeyboardButton(\"✅ Thiha\" if \"Thiha\" in voice_name else \"🎙️ Thiha\", callback_data=\"voice_thiha\")\n",
    "    nilar_cb = types.InlineKeyboardButton(\"✅ Nilar\" if \"Nilar\" in voice_name else \"🎙️ Nilar\", callback_data=\"voice_nilar\")\n",
    "    keyboard.add(thiha_cb, nilar_cb)\n",
    "    \n",
    "    # Speed row\n",
    "    keyboard.add(types.InlineKeyboardButton(\"⚡ Speed: \" + str(settings['speed']), callback_data=\"noop\"))\n",
    "    speed_row = [types.InlineKeyboardButton(\"-10\", callback_data=\"speed_-10\")]\n",
    "    for s in [20, 30, 40, 50, 60, 70, 80]:\n",
    "        btn = types.InlineKeyboardButton(str(s) if settings['speed'] != s else \"[\" + str(s) + \"]\", callback_data=\"speed_\" + str(s))\n",
    "        speed_row.append(btn)\n",
    "    speed_row.append(types.InlineKeyboardButton(\"+10\", callback_data=\"speed_+10\"))\n",
    "    keyboard.add(*speed_row)\n",
    "    \n",
    "    # Pitch row\n",
    "    keyboard.add(types.InlineKeyboardButton(\"🎵 Pitch: \" + str(settings['pitch']), callback_data=\"noop\"))\n",
    "    pitch_row = [types.InlineKeyboardButton(\"-10\", callback_data=\"pitch_-10\")]\n",
    "    for p in [20, 30, 40, 50, 60, 70, 80]:\n",
    "        btn = types.InlineKeyboardButton(str(p) if settings['pitch'] != p else \"[\" + str(p) + \"]\", callback_data=\"pitch_\" + str(p))\n",
    "        pitch_row.append(btn)\n",
    "    pitch_row.append(types.InlineKeyboardButton(\"+10\", callback_data=\"pitch_+10\"))\n",
    "    keyboard.add(*pitch_row)\n",
    "    \n",
    "    # Skip button LAST (bottom)\n",
    "    skip_btn = types.InlineKeyboardButton(\"⏭️ Skip (Default)\", callback_data=\"skip_settings\")\n",
    "    ask_btn = types.InlineKeyboardButton(\"💡 Ask AI about this\", callback_data=\"ask_ai_media\")\n",
    "    keyboard.add(skip_btn, ask_btn)\n",
    "    \n",
    "    sent = bot.send_message(chat_id, msg, reply_markup=keyboard)\n",
    "    return sent\n",
    "\n",
    "\n",
    "def get_duration(file_path):\n",
    "    \"\"\"Get duration of media file in seconds using ffprobe.\"\"\"\n",
    "    try:\n",
    "        cmd = f\"ffprobe -v error -show_entries format=duration -of default=noprint_wrappers=1:nokey=1 '{file_path}'\"\n",
    "        output = subprocess.check_output(cmd, shell=True).decode('utf-8').strip()\n",
    "        return float(output)\n",
    "    except:\n",
    "        return None\n",
    "\n",
    "def process_media_qa(chat_id, media_type, file_data, question):\n",
    "    \"\"\"Handle Q&A for media files.\"\"\"\n",
    "    status_msg = bot.send_message(chat_id, \"👁️ Media ကို လေ့လာနေပါတယ်...\")\n",
    "    try:\n",
    "        temp_file = tempfile.mktemp(suffix='.mp4' if media_type == 'video' else '.mp3')\n",
    "        with open(temp_file, 'wb') as f:\n",
    "            f.write(file_data)\n",
    "        \n",
    "        file_size_mb = os.path.getsize(temp_file) / (1024 * 1024)\n",
    "        mime_type = \"video/mp4\" if media_type == \"video\" else \"audio/mp3\"\n",
    "        \n",
    "        if file_size_mb < 19:\n",
    "            with open(temp_file, 'rb') as f:\n",
    "                b64_data = base64.b64encode(f.read()).decode('utf-8')\n",
    "            parts = [\n",
    "                {\"text\": question},\n",
    "                {\"inline_data\": {\"mime_type\": mime_type, \"data\": b64_data}}\n",
    "            ]\n",
    "            ai_response = gemini_generate([{\"role\": \"user\", \"parts\": parts}], chat_id=chat_id)\n",
    "        else:\n",
    "            bot.edit_message_text(\"⏳ ဖိုင်ဆိုဒ်ကြီးလို့ ခဏစောင့်ပေးပါ...\", chat_id, status_msg.message_id)\n",
    "            ai_response = \"⚠️ ဖိုင်ဆိုဒ် 20MB ထက်ကြီးတဲ့အတွက် Q&A လုပ်ဖို့ ခက်ခဲနေပါတယ်။ Movie Recap ကိုပဲ အသုံးပြုပေးပါ။\"\n",
    "\n",
    "        safe_send(chat_id, ai_response, status_msg.message_id, is_edit=True)\n",
    "        os.remove(temp_file)\n",
    "    except Exception as e:\n",
    "        bot.send_message(chat_id, f\"❌ Error: {str(e)}\")\n",
    "\n",
    "def process_media(chat_id, media_type, file_data, status_msg_id):\n",
    "    \"\"\"Process the stored media - transcribe, translate, TTS, SRT.\"\"\"\n",
    "    temp_ogg = None\n",
    "    temp_video = None\n",
    "    mp3_file = None\n",
    "    audio_file = None\n",
    "    srt_file = None\n",
    "    \n",
    "    try:\n",
    "        duration = None\n",
    "        if media_type == \"voice\":\n",
    "            bot.edit_message_text(\"📥 Downloading...\", chat_id, status_msg_id)\n",
    "            file_bytes = file_data\n",
    "            temp_ogg = tempfile.mktemp(suffix='.ogg')\n",
    "            with open(temp_ogg, 'wb') as f:\n",
    "                f.write(file_bytes)\n",
    "            mp3_file = tempfile.mktemp(suffix='.mp3')\n",
    "            ret = os.system(f\"ffmpeg -i '{temp_ogg}' -y '{mp3_file}' 2>/dev/null\")\n",
    "            process_file = mp3_file if (ret == 0 and os.path.exists(mp3_file) and os.path.getsize(mp3_file) > 0) else temp_ogg\n",
    "            duration = get_duration(process_file)\n",
    "        else:\n",
    "            bot.edit_message_text(\"📥 Downloading video...\", chat_id, status_msg_id)\n",
    "            file_bytes = file_data\n",
    "            temp_video = tempfile.mktemp(suffix='.mp4')\n",
    "            with open(temp_video, 'wb') as f:\n",
    "                f.write(file_bytes)\n",
    "            size_mb = os.path.getsize(temp_video) / (1024 * 1024)\n",
    "            bot.edit_message_text(f\"📊 Video: {size_mb:.1f}MB\\n🤖 Processing...\", chat_id, status_msg_id)\n",
    "            process_file = temp_video\n",
    "            duration = get_duration(process_file)\n",
    "        \n",
    "        bot.edit_message_text(\"🤖 Gemini နဲ့ ဘာသာပြန်နေပါတယ်...\", chat_id, status_msg_id)\n",
    "        ftype = \"audio\" if media_type == \"voice\" else \"video\"\n",
    "        myanmar_text = transcribe_and_translate(process_file, file_type=ftype, duration_sec=duration, chat_id=chat_id)\n",
    "        \n",
    "        if myanmar_text.startswith(\"Error\") or myanmar_text.startswith(\"API Error\"):\n",
    "            bot.send_message(chat_id, f\"❌ Translation error: {myanmar_text[:500]}\")\n",
    "            return\n",
    "        \n",
    "        safe_send(chat_id, \"🇲🇲 Myanmar Recap:\\n\\n\" + myanmar_text, status_msg_id, is_edit=True)\n",
    "        \n",
    "        bot.send_message(chat_id, \"🔊 Audio create လုပ်နေပါတယ်...\")\n",
    "        audio_file = tempfile.mktemp(suffix='.mp3')\n",
    "        srt_file = tempfile.mktemp(suffix='.srt')\n",
    "        \n",
    "        if text_to_speech_myanmar(myanmar_text, audio_file, chat_id=chat_id):\n",
    "            with open(audio_file, 'rb') as audio:\n",
    "                bot.send_audio(chat_id, audio, caption=\"🔊 Myanmar Audio\", title=\"Myanmar Recap Audio\")\n",
    "            \n",
    "            # Get the actual duration of the generated Myanmar audio\n",
    "            myanmar_audio_duration = get_duration(audio_file)\n",
    "            generate_srt(myanmar_text, srt_file, audio_duration=myanmar_audio_duration)\n",
    "            if os.path.exists(srt_file) and os.path.getsize(srt_file) > 0:\n",
    "                with open(srt_file, 'rb') as srt:\n",
    "                    bot.send_document(chat_id, srt, caption=\"📝 SRT Subtitle (CapCut)\")\n",
    "        else:\n",
    "            bot.send_message(chat_id, \"⚠️ Audio create မရပါ\")\n",
    "        \n",
    "        bot.send_message(chat_id, \"✅ Completed! 🎬\")\n",
    "    \n",
    "    except Exception as e:\n",
    "        try:\n",
    "            bot.edit_message_text(\"❌ Error: \" + str(e)[:400], chat_id, status_msg_id)\n",
    "        except:\n",
    "            bot.send_message(chat_id, \"❌ Error: \" + str(e)[:400])\n",
    "        print(\"[Error] \" + str(e))\n",
    "    \n",
    "    finally:\n",
    "        for f in [temp_ogg, temp_video, mp3_file, audio_file, srt_file]:\n",
    "            if f and os.path.exists(f):\n",
    "                try:\n",
    "                    os.remove(f)\n",
    "                except:\n",
    "                    pass\n",
    "\n",
    "\n",
    "@bot.message_handler(content_types=['voice'])\n",
    "def handle_voice(message):\n",
    "    chat_id = message.chat.id\n",
    "    try:\n",
    "        file_info = bot.get_file(message.voice.file_id)\n",
    "        file_bytes = bot.download_file(file_info.file_path)\n",
    "    except Exception as e:\n",
    "        bot.send_message(chat_id, \"❌ File download error: \" + str(e)[:300])\n",
    "        return\n",
    "    \n",
    "    show_settings_for_processing(chat_id, \"voice\", file_bytes)\n",
    "\n",
    "\n",
    "@bot.message_handler(content_types=['video'])\n",
    "def handle_video(message):\n",
    "    chat_id = message.chat.id\n",
    "\n",
    "    if hasattr(message.video, 'file_size') and message.video.file_size:\n",
    "        size_mb = message.video.file_size / (1024 * 1024)\n",
    "        if size_mb > MAX_VIDEO_SIZE_MB:\n",
    "            bot.send_message(chat_id, f\"❌ Video ကြီးလွန်းပါတယ်! ({size_mb:.1f}MB / max {MAX_VIDEO_SIZE_MB}MB)\")\n",
    "            return\n",
    "\n",
    "    try:\n",
    "        file_info = bot.get_file(message.video.file_id)\n",
    "        file_bytes = bot.download_file(file_info.file_path)\n",
    "    except Exception as e:\n",
    "        bot.send_message(chat_id, \"❌ File download error: \" + str(e)[:300])\n",
    "        return\n",
    "    \n",
    "    show_settings_for_processing(chat_id, \"video\", file_bytes)\n",
    "\n",
    "\n",
    "@bot.message_handler(content_types=['photo'])\n",
    "def handle_photo(message):\n",
    "    \"\"\"Handle photo messages for AI vision.\"\"\"\n",
    "    chat_id = message.chat.id\n",
    "    caption = message.caption or \"Describe this image in detail in Myanmar language.\"\n",
    "    \n",
    "    status_msg = bot.reply_to(message, \"👁️ ပုံကို ကြည့်နေပါတယ်...\")\n",
    "    \n",
    "    try:\n",
    "        file_info = bot.get_file(message.photo[-1].file_id)\n",
    "        file_bytes = bot.download_file(file_info.file_path)\n",
    "        file_data = base64.b64encode(file_bytes).decode('utf-8')\n",
    "        \n",
    "        history = get_history(chat_id)\n",
    "        current_parts = [\n",
    "            {\"text\": caption},\n",
    "            {\"inline_data\": {\"mime_type\": \"image/jpeg\", \"data\": file_data}}\n",
    "        ]\n",
    "        \n",
    "        contents = history + [{\"role\": \"user\", \"parts\": current_parts}]\n",
    "        full_response = \"\"\n",
    "        last_edit_time = time.time()\n",
    "        generator = gemini_generate(contents, stream=True, chat_id=chat_id)\n",
    "        \n",
    "        for chunk in generator:\n",
    "            full_response += chunk\n",
    "            if time.time() - last_edit_time > 2.0:\n",
    "                try:\n",
    "                    bot.edit_message_text(full_response + \" ▌\", chat_id, status_msg.message_id)\n",
    "                    last_edit_time = time.time()\n",
    "                except: pass\n",
    "        \n",
    "        if not full_response:\n",
    "            bot.edit_message_text(\"❌ အဖြေမရရှိပါ\", chat_id, status_msg.message_id)\n",
    "            return\n",
    "\n",
    "        add_to_history(chat_id, \"user\", caption, parts=current_parts)\n",
    "        add_to_history(chat_id, \"model\", full_response)\n",
    "        safe_send(chat_id, full_response, status_msg.message_id, is_edit=True)\n",
    "            \n",
    "    except Exception as e:\n",
    "        bot.edit_message_text(f\"❌ Error: {str(e)[:400]}\", chat_id, status_msg.message_id)\n",
    "\n",
    "\n",
    "@bot.message_handler(commands=['clear'])\n",
    "def clear_history(message):\n",
    "    chat_id = message.chat.id\n",
    "    if chat_id in chat_histories:\n",
    "        chat_histories[chat_id] = []\n",
    "    bot.reply_to(message, \"🧹 မှတ်ဉာဏ်တွေကို ရှင်းလင်းလိုက်ပါပြီ။ အသစ်ကနေ ပြန်စကားပြောလို့ရပါပြီ။\")\n",
    "\n",
    "@bot.message_handler(func=lambda message: True)\n",
    "def handle_text_chat(message):\n",
    "    \"\"\"Handle text messages for AI chat.\"\"\"\n",
    "    chat_id = message.chat.id\n",
    "    user_text = message.text\n",
    "    \n",
    "    if not user_text or user_text.startswith('/'):\n",
    "        return\n",
    "    \n",
    "    # Check if user is asking a question about pending media\n",
    "    if chat_id in pending_requests and pending_requests[chat_id].get(\"awaiting_question\"):\n",
    "        pending = pending_requests.pop(chat_id)\n",
    "        process_media_qa(chat_id, pending[\"media_type\"], pending[\"file_data\"], user_text)\n",
    "        return\n",
    "        \n",
    "    status_msg = bot.reply_to(message, \"🤔 စဉ်းစားနေပါတယ်...\")\n",
    "    \n",
    "    try:\n",
    "        # Check for image generation keywords\n",
    "        img_keywords = [\"draw\", \"generate image\", \"create image\", \"ပုံဆွဲ\", \"ပုံထုတ်\", \"ရုပ်ပုံ\"]\n",
    "        is_img_request = any(k in user_text.lower() for k in img_keywords)\n",
    "        \n",
    "        if is_img_request:\n",
    "            status_msg = bot.reply_to(message, \"🎨 ပုံဆွဲပေးနေပါတယ်... ခဏစောင့်ပေးပါ\")\n",
    "            # Use Gemini to create a better English prompt for the image\n",
    "            prompt_refiner = f\"Create a detailed English image generation prompt for: {user_text}. Return ONLY the prompt text.\"\n",
    "            refined_prompt = gemini_generate([{\"role\": \"user\", \"parts\": [{\"text\": prompt_refiner}]}], stream=False, chat_id=chat_id)\n",
    "            \n",
    "            img_url = generate_image(refined_prompt)\n",
    "            bot.send_photo(chat_id, img_url, caption=f\"✨ {user_text}\")\n",
    "            bot.delete_message(chat_id, status_msg.message_id)\n",
    "            return\n",
    "\n",
    "        history = get_history(chat_id)\n",
    "        contents = history + [{\"role\": \"user\", \"parts\": [{\"text\": user_text}]}]\n",
    "        \n",
    "        full_response = \"\"\n",
    "        last_edit_time = time.time()\n",
    "        \n",
    "        # Use streaming for a better chat experience\n",
    "        generator = gemini_generate(contents, stream=True, chat_id=chat_id)\n",
    "        \n",
    "        for chunk in generator:\n",
    "            full_response += chunk\n",
    "            # Edit message every 2 seconds to avoid Telegram rate limits\n",
    "            if time.time() - last_edit_time > 2.0:\n",
    "                try:\n",
    "                    bot.edit_message_text(full_response + \" ▌\", chat_id, status_msg.message_id)\n",
    "                    last_edit_time = time.time()\n",
    "                except: pass\n",
    "        \n",
    "        if not full_response:\n",
    "            bot.edit_message_text(\"❌ အဖြေမရရှိပါ\", chat_id, status_msg.message_id)\n",
    "            return\n",
    "\n",
    "        add_to_history(chat_id, \"user\", user_text)\n",
    "        add_to_history(chat_id, \"model\", full_response)\n",
    "        \n",
    "        # Final update without the cursor\n",
    "        safe_send(chat_id, full_response, status_msg.message_id, is_edit=True)\n",
    "            \n",
    "    except Exception as e:\n",
    "        bot.edit_message_text(f\"❌ Error: {str(e)[:400]}\", chat_id, status_msg.message_id)\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# START BOT\n",
    "# ============================================================\n",
    "\n",
    "print(\"=\" * 50)\n",
    "print(\"🎬 MOVIE RECAP TRANSLATOR BOT\")\n",
    "print(\"=\" * 50)\n",
    "\n",
    "if TELEGRAM_BOT_TOKEN == \"YOUR_TELEGRAM_BOT_TOKEN_HERE\":\n",
    "    print(\"❌ Token မသတ်မှတ်ရသေးပါ!\")\n",
    "else:\n",
    "    print(\"✅ Token: Set\")\n",
    "    print(\"✅ Model: gemini-3.5-flash\")\n",
    "    print(\"🚀 Bot starting with retry logic...\")\n",
    "    print(\"⚠️ Connection errors will auto-retry\")\n",
    "    print(\"=\" * 50)\n",
    "\n",
    "    # Configure bot with retry and longer timeouts\n",
    "    # Note: callback_query updates must be in allowed_updates for buttons to work\n",
    "    print(f\"📋 Callback handlers registered: {len(bot.callback_query_handlers)}\")\n",
    "    print(f\"📋 Message handlers registered: {len(bot.message_handlers)}\")\n",
    "    import PyPDF2\n",
    "    \n",
    "    @bot.message_handler(content_types=['document'])\n",
    "    def handle_document(message):\n",
    "        chat_id = message.chat.id\n",
    "        file_name = message.document.file_name\n",
    "        \n",
    "        status_msg = bot.reply_to(message, f\"📄 {file_name} ကို ဖတ်နေပါတယ်...\")\n",
    "        \n",
    "        try:\n",
    "            file_info = bot.get_file(message.document.file_id)\n",
    "            file_bytes = bot.download_file(file_info.file_path)\n",
    "            \n",
    "            text_content = \"\"\n",
    "            if file_name.lower().endswith('.pdf'):\n",
    "                with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as f:\n",
    "                    f.write(file_bytes)\n",
    "                    temp_path = f.name\n",
    "                with open(temp_path, 'rb') as f:\n",
    "                    reader = PyPDF2.PdfReader(f)\n",
    "                    for page in reader.pages:\n",
    "                        text_content += page.extract_text() + \"\\n\"\n",
    "                os.remove(temp_path)\n",
    "            elif file_name.lower().endswith(('.txt', '.py', '.md')):\n",
    "                text_content = file_bytes.decode('utf-8')\n",
    "            else:\n",
    "                bot.edit_message_text(\"⚠️ ဒီလိုဖိုင်မျိုးကိုတော့ မဖတ်တတ်သေးပါဘူးခင်ဗျာ။ PDF သို့မဟုတ် Text ဖိုင်ပဲ ပို့ပေးပါ။\", chat_id, status_msg.message_id)\n",
    "                return\n",
    "            \n",
    "            prompt = f\"I have uploaded a document named '{file_name}'. Here is its content:\\n\\n{text_content[:30000]}\\n\\nPlease summarize this document in Myanmar language.\"\n",
    "            \n",
    "            history = get_history(chat_id)\n",
    "            contents = history + [{\"role\": \"user\", \"parts\": [{\"text\": prompt}]}]\n",
    "            full_response = \"\"\n",
    "            last_edit_time = time.time()\n",
    "            generator = gemini_generate(contents, stream=True, chat_id=chat_id)\n",
    "            \n",
    "            for chunk in generator:\n",
    "                full_response += chunk\n",
    "                if time.time() - last_edit_time > 2.0:\n",
    "                    try:\n",
    "                        bot.edit_message_text(full_response + \" ▌\", chat_id, status_msg.message_id)\n",
    "                        last_edit_time = time.time()\n",
    "                    except: pass\n",
    "            \n",
    "            if not full_response:\n",
    "                bot.edit_message_text(\"❌ အဖြေမရရှိပါ\", chat_id, status_msg.message_id)\n",
    "                return\n",
    "\n",
    "            add_to_history(chat_id, \"user\", f\"[Uploaded Document: {file_name}]\")\n",
    "            add_to_history(chat_id, \"model\", full_response)\n",
    "            safe_send(chat_id, full_response, status_msg.message_id, is_edit=True)\n",
    "                \n",
    "        except Exception as e:\n",
    "            bot.edit_message_text(f\"❌ Error: {str(e)[:400]}\", chat_id, status_msg.message_id)\n",
    "\n",
    "    \n",
    "\n",
    "def transcribe_and_translate(file_path, file_type=\"audio\", duration_sec=None, chat_id=None):\n",
    "    \"\"\"Transcribe and translate in one step for speed.\"\"\"\n",
    "    file_size_mb = os.path.getsize(file_path) / (1024 * 1024)\n",
    "    mime_type = \"audio/mp3\" if file_type == \"audio\" else \"video/mp4\"\n",
    "    \n",
    "    duration_info = \"\"\n",
    "    if duration_sec:\n",
    "        target_word_count = int(duration_sec * 2.8)\n",
    "        duration_info = f\"\\n- TARGET LENGTH: Approximately {target_word_count} Myanmar words.\\n- The original video duration is {int(duration_sec)} seconds. Ensure your narration fits this timeframe.\"\n",
    "\n",
    "    prompt = f\"\"\"You are a professional movie recap expert and Myanmar translator. \n",
    "Your task is to:\n",
    "1. Listen to the provided file.\n",
    "2. Translate the content directly into Myanmar language in the dramatic storytelling style of \"Thiha Voice\" (movie recap channel).\n",
    "\n",
    "IMPORTANT RULES:\n",
    "- ONLY translate what is in the audio/video. DO NOT add any extra content, scenes, or information not mentioned.\n",
    "- DO NOT invent new plot points, characters, or events.\n",
    "- DO NOT write an intro or outro that is not in the original content.{duration_info}\n",
    "- Provide a COMPREHENSIVE yet EFFICIENT narration.\n",
    "- Maintain a natural movie recap pace - engaging and detailed.\n",
    "- Use dramatic, engaging narration tone (voice ကြမ်းကြမ်း၊ ဆွဲဆွဲငင်ငင်).\n",
    "- Use colloquial Myanmar storytelling phrases naturally like \"ဆိုပြီး...\", \"ဒီမှာတော့...\", \"ဆိုတဲ့အခါမှာ...\", \"ဒါပေမယ့်...\", \"ဆိုတာကတော့...\".\n",
    "- Write ENTIRELY in Myanmar language in paragraphs.\n",
    "\n",
    "Provide the complete Myanmar narration.\"\"\"\n",
    "\n",
    "    if file_size_mb < 19:\n",
    "        with open(file_path, 'rb') as f:\n",
    "            file_data = base64.b64encode(f.read()).decode('utf-8')\n",
    "        contents = [{\n",
    "            \"role\": \"user\",\n",
    "            \"parts\": [\n",
    "                {\"text\": prompt},\n",
    "                {\"inline_data\": {\"mime_type\": mime_type, \"data\": file_data}}\n",
    "            ]\n",
    "        }]\n",
    "        return gemini_generate(contents, chat_id=chat_id)\n",
    "    else:\n",
    "        # Large file upload logic\n",
    "        file_size = os.path.getsize(file_path)\n",
    "        upload_url = \"https://generativelanguage.googleapis.com/upload/v1beta/files\"\n",
    "        headers = {\n",
    "            \"x-goog-api-key\": get_current_key(),\n",
    "            \"X-Goog-Upload-Protocol\": \"resumable\",\n",
    "            \"X-Goog-Upload-Command\": \"start\",\n",
    "            \"X-Goog-Upload-Header-Content-Length\": str(file_size),\n",
    "            \"X-Goog-Upload-Header-Content-Type\": mime_type,\n",
    "            \"Content-Type\": \"application/json\"\n",
    "        }\n",
    "        data = json.dumps({\"file\": {\"display_name\": \"upload\"}}).encode('utf-8')\n",
    "        req = urllib.request.Request(upload_url, data=data, headers=headers, method='POST')\n",
    "        resp = urllib.request.urlopen(req)\n",
    "        upload_location = resp.headers.get('X-Goog-Upload-URL')\n",
    "\n",
    "        with open(file_path, 'rb') as f:\n",
    "            file_data = f.read()\n",
    "        headers2 = {\n",
    "            \"Content-Length\": str(file_size),\n",
    "            \"X-Goog-Upload-Offset\": \"0\",\n",
    "            \"X-Goog-Upload-Command\": \"upload, finalize\"\n",
    "        }\n",
    "        req2 = urllib.request.Request(upload_location, data=file_data, headers=headers2, method='POST')\n",
    "        resp2 = urllib.request.urlopen(req2)\n",
    "        upload_result = json.loads(resp2.read().decode('utf-8'))\n",
    "        file_uri = upload_result['file']['uri']\n",
    "        file_name = upload_result['file']['name']\n",
    "\n",
    "        for attempt in range(60):\n",
    "            check_url = f\"https://generativelanguage.googleapis.com/v1beta/{file_name}?key={get_current_key()}\"\n",
    "            req_check = urllib.request.Request(check_url)\n",
    "            resp_check = urllib.request.urlopen(req_check)\n",
    "            status = json.loads(resp_check.read().decode('utf-8'))\n",
    "            if status.get('state') == 'ACTIVE': break\n",
    "            elif status.get('state') == 'FAILED': return \"File processing failed.\"\n",
    "            time.sleep(5)\n",
    "\n",
    "        contents = [{\n",
    "            \"role\": \"user\",\n",
    "            \"parts\": [\n",
    "                {\"text\": prompt},\n",
    "                {\"file_data\": {\"file_uri\": file_uri, \"mime_type\": mime_type}}\n",
    "            ]\n",
    "        }]\n",
    "        return gemini_generate(contents, chat_id=chat_id)\n",
    "\n",
    "\n",
    "\n",
    "bot.infinity_polling(\n",
    "        timeout=60,\n",
    "        long_polling_timeout=60,\n",
    "        allowed_updates=[\"message\", \"edited_message\", \"callback_query\", \"photo\", \"document\"]\n",
    "    )\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    ""
   ],
   "outputs": []
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Quick Guide\n",
    "\n",
    "1. Cell 1 → run (install)\n",
    "2. Cell 2 → run (tokens set)\n",
    "3. Cell 3 → run (bot starts)\n",
    "4. Telegram မှာ voice/video ပို့ပါ\n",
    "\n",
    "Stop: cell ■ button နှိပ်ပါ\n",
    "Restart: Runtime → Restart runtime"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.11.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
